import { DeliveryCompany, Language, OrderStatus, Permission } from './types';

// Add new translation keys here. The English key will be used as a fallback if the Arabic one is missing.
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // General
    brandName: 'Pakomi',
    english: 'English',
    arabic: 'Arabic',
    close: 'Close',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    edit: 'Edit',
    delete: 'Delete',
    add: 'Add',
    enabled: 'Enabled',
    required: 'Required',
    backToHome: 'Back to Home',
    continueShopping: 'Continue Shopping',
    copied: 'Copied!',
    copyId: 'Copy ID',
    submit: 'Submit',

    // Header & Navigation
    myAccount: 'My Account',
    logout: 'Logout',
    login: 'Login',
    signUp: 'Sign Up',
    register: 'Register',
    trackOrder: 'Track Order',
    adminPanel: 'Admin Panel',
    shoppingCart: 'Shopping Cart',

    // Home Page
    selectYourProduct: 'Select Your Product',
    ourServices: 'Our Services',
    whatOurClientsSay: 'What Our Clients Say',
    howItWorks: 'How It Works',
    faqSection: "Frequently Asked Questions",

    // Customization Modal/Page
    customizeYourPackaging: 'Customize Your Product',
    livePreview: 'Live Preview',
    changeColor: 'Change Color',
    selectColor: 'Select Color',

    // Customization Form
    specifications: 'Specifications',
    dimensions: 'Dimensions (cm)',
    selectSize: 'Select a standard size, or enter custom dimensions below.',
    customDimensions: 'or enter custom dimensions',
    width: 'Width',
    height: 'Height',
    depth: 'Depth',
    gusset: 'Gusset',
    tooltipWidthBox: 'The horizontal dimension of the box front.',
    tooltipHeightBox: 'The vertical dimension of the box front.',
    tooltipDepthBox: 'The side dimension of the box.',
    tooltipWidthShoppingBag: 'The horizontal dimension of the bag front.',
    tooltipHeightShoppingBag: 'The vertical dimension of the bag front.',
    tooltipGussetShoppingBag: 'The depth of the side panel of the bag.',
    tooltipWidthBusinessCard: 'The horizontal dimension of the card.',
    tooltipHeightBusinessCard: 'The vertical dimension of the card.',
    color: 'Color',
    quantityAndPrice: 'Quantity & Price',
    quantity: 'Quantity',
    pricePerItem: 'Price per item',
    totalPrice: 'Total Price',
    bulkDiscount: 'Bulk discount applied!',
    customSizeQuote: 'Contact Us for a Custom Size Quote',
    addToCart: 'Add to Cart',
    orderNow: 'Order Now & Checkout',
    itemAddedToCart: 'Item added to cart!',
    uploadYourLogoOptional: 'Upload Your Logo (Optional)',
    uploadLogo: 'Upload Logo',
    logoUploadHelpText: 'PNG, JPG, SVG, PDF, PSD, AI up to 2MB',
    logoUploaded: 'Logo uploaded',
    removeLogo: 'Remove logo',
    yourDetails: 'Your Details',
    description: 'Description / Notes',
    descriptionPlaceholder: 'Any special instructions or notes about your design...',
    clientName: 'Full Name',
    phone: 'Phone Number',
    phonePlaceholder: 'e.g., 0512345678',
    wilaya: 'State (Wilaya)',
    selectWilaya: 'Select a Wilaya',
    commune: 'City (Commune)',
    selectCommune: 'Select a Commune',
    address: 'Address',
    socialMedia: 'Social Media (Optional)',
    platform: 'Platform',
    urlPlaceholder: 'https://...',
    url: 'URL',
    addSocialLink: 'Add another social link',
    removeSocialLink: 'Remove social link',
    whatsapp: 'WhatsApp',
    viber: 'Viber',
    
    // Cart & Checkout
    emptyCart: 'Your cart is empty.',
    proceedToCheckout: 'Proceed to Checkout',
    checkout: 'Checkout',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    
    // Order Tracking
    trackYourOrder: 'Track Your Order',
    trackOrderPrompt: 'Enter your order ID below to see its status.',
    enterOrderId: 'Enter your Order ID',
    track: 'Track',
    orderNotFound: 'Order not found. Please check the ID and try again.',
    orderDetails: 'Order Details',
    orderId: 'Order ID',
    submittedOn: 'Submitted On',
    shippingInfo: 'Shipping Info',
    carrier: 'Carrier',
    trackingNumber: 'Tracking Number',
    products: 'Products',
    status: 'Status',
    chatWithUs: 'Chat With Us',
    typeYourMessage: 'Type your message...',
    attachFile: 'Attach File',
    removeFile: 'Remove file',
    sendMessage: 'Send Message',
    orderPlaced: 'Order Placed',
    designing: 'Designing',
    printing: 'Printing',
    packaging: 'Packaging',
    shipped: 'Shipped',
    completed: 'Completed',
    cancelled: 'Cancelled',
    pending: 'Pending',
    'in production': 'In Production', // For status dropdown

    // Thank You & Feedback
    orderSubmittedSuccess: 'Order Submitted!',
    yourTrackingIdIs: 'Your tracking ID is:',
    leaveAReview: 'Leave a Review',
    feedbackSubmitted: 'Thank You!',
    howWasYourExperience: 'How was your experience with your order?',
    rating: 'Your Rating',
    comments: 'Comments (Optional)',
    submitFeedback: 'Submit Feedback',
    reviewAlreadySubmitted: 'You have already submitted a review for this order.',
    
    // Admin
    manageOrders: 'Manage Orders',
    filterByStatus: 'Filter by status',
    all: 'All',
    submittedAt: 'Date',
    actions: 'Actions',
    chat: 'Chat',
    viewDetails: 'View Details',
    noOrdersFound: 'No orders found for this filter.',
    ordersSelected: '{count} orders selected',
    changeStatus: 'Change status for selected',
    apply: 'Apply',
    deselectAll: 'Deselect All',
    contactInformation: 'Contact Information',
    itemWeight: 'Item Weight',
    totalWeight: 'Total Weight',
    chatWithCustomer: 'Chat with Customer',
    shipOrder: 'Ship Order',
    deliveryCompany: 'Delivery Company',
    markAsShipped: 'Mark as Shipped',
    creatingShipment: 'Creating Shipment...',
    failedToCreateShipment: 'Failed to create shipment',
    corsErrorExplanation: 'This is likely a CORS policy error because this is a demo app without a backend proxy. A mock tracking number will be used instead.',
    corsErrorTechnicalSolution: 'In a real app, this would be solved by calling your own backend, which then calls the delivery API.',
    downloadLogo: 'Download Client Logo',
    editOrder: 'Edit Order',
    saveOrder: 'Save Order',
    addProduct: 'Add Product',
    removeItem: 'Remove Item',
    confirmRemoveItem: 'Are you sure you want to remove this item from the order?',
    cannotSaveEmptyOrder: 'Cannot save an order with no items. Please cancel the order instead.',
    productEditor: 'Product Editor',
    addNewProduct: 'New Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    confirmDeleteProduct: 'Are you sure you want to delete this product and all its associated sizes?',
    productName: 'Product Name',
    productImage: 'Product Image',
    availableColors: 'Available Colors',
    colorName: 'Color Name',
    colorValue: 'Color Value',
    addColor: 'Add Color',
    dragToReorder: 'Drag to re-order',
    sizes: 'Sizes',
    addNewSize: 'New Size',
    editSize: 'Edit Size',
    deleteSize: 'Delete Size',
    confirmDelete: 'Are you sure?',
    weightGrams: 'Weight (g)',
    pricingTiers: 'Pricing Tiers',
    minQuantity: 'Min. Quantity',
    price: 'Price',
    addTier: 'Add Tier',
    'No sizes configured for this product.': 'No sizes configured for this product.',
    'to manage its sizes': 'to manage its sizes',
    formEditor: 'Form Editor',
    formEditorDescription: 'Customize the fields and sections visible to customers during product customization.',
    generalSettings: 'General Settings',
    logo: 'Logo',
    homepageContent: 'Homepage Content',
    heroSection: 'Hero Section',
    mainHeadline: 'Main Headline',
    subHeadline: 'Sub-headline',
    ctaButtonText: 'Call-to-Action Button Text',
    heroImage: 'Hero Image',
    addNewservice: 'New Service',
    addNewstep: 'New Step',
    addNewtestimonial: 'New Testimonial',
    addNewquestion: 'New Question',
    imageUrl: 'Image URL',
    icon: "Icon Name (e.g. select, order, ship)",
    thankYouPageSettings: 'Thank You Page Settings',
    thankYouTitle: 'Thank You Title',
    thankYouMessage: 'Thank You Message',
    upsellSection: 'Upsell Section',
    enableUpsell: 'Enable Upsell Section',
    upsellTitle: 'Upsell Title',
    productsToShow: 'Products to Show',
    trackingAndAnalytics: 'Tracking & Analytics',
    facebookPixelId: 'Facebook Pixel ID',
    tiktokPixelId: 'TikTok Pixel ID',
    snapchatPixelId: 'Snapchat Pixel ID',
    googleAnalyticsId: 'Google Analytics ID (G-...)',
    footerContent: 'Footer Content',
    addLink: 'Add Link',
    saved: 'Saved!',
    toDo: 'To-Do List',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    priority: 'Priority',
    newTaskPlaceholder: 'What needs to be done?',
    addTask: 'Add Task',
    sortBy: 'Sort by',
    sortByPriority: 'Priority',
    sortByDate: 'Date',
    noTasks: 'All clear! No tasks here.',
    usersAndRoles: 'Users & Roles',
    users: 'Users',
    roles: 'Roles',
    permissions: 'Permissions',
    addNewRole: 'Add New Role',
    editRole: 'Edit Role',
    roleName: 'Role Name',
    userManagement: 'User Management',
    roleManagement: 'Role Management',
    customers: 'Customers',
    staff: 'Staff',
    role: 'Role',
    confirmDeleteUser: 'Are you sure you want to delete this user? This action cannot be undone.',
    confirmDeleteRole: 'Are you sure you want to delete this role? Users with this role will be reassigned to the Customer role.',
    cannotDeleteEssentialRole: 'Cannot delete the essential "{roleName}" role.',


    // Auth
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    myOrders: 'My Orders',
    orderDate: 'Order Date',
    noOrdersYet: 'You haven\'t placed any orders yet.',
  },
  ar: {
    // General
    brandName: 'باكومي',
    english: 'English',
    arabic: 'العربية',
    close: 'إغلاق',
    cancel: 'إلغاء',
    saveChanges: 'حفظ التغييرات',
    edit: 'تعديل',
    delete: 'حذف',
    add: 'إضافة',
    enabled: 'مفعل',
    required: 'مطلوب',
    backToHome: 'العودة للرئيسية',
    continueShopping: 'متابعة التسوق',
    copied: 'تم النسخ!',
    copyId: 'نسخ المعرف',
    submit: 'إرسال',

    // Header & Navigation
    myAccount: 'حسابي',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    register: 'تسجيل',
    trackOrder: 'تتبع الطلب',
    adminPanel: 'لوحة التحكم',
    shoppingCart: 'سلة التسوق',

    // Home Page
    selectYourProduct: 'اختر منتجك',
    ourServices: 'خدماتنا',
    whatOurClientsSay: 'ماذا يقول عملاؤنا',
    howItWorks: 'كيف نعمل',
    faqSection: "الأسئلة الشائعة",

    // Customization Modal/Page
    customizeYourPackaging: 'تخصيص منتجك',
    livePreview: 'معاينة حية',
    changeColor: 'تغيير اللون',
    selectColor: 'اختر اللون',

    // Customization Form
    specifications: 'المواصفات',
    dimensions: 'الأبعاد (سم)',
    selectSize: 'اختر حجمًا قياسيًا، أو أدخل أبعادًا مخصصة أدناه.',
    customDimensions: 'أو أدخل أبعادًا مخصصة',
    width: 'العرض',
    height: 'الارتفاع',
    depth: 'العمق',
    gusset: 'الكعب',
    tooltipWidthBox: 'البعد الأفقي لواجهة الصندوق.',
    tooltipHeightBox: 'البعد العمودي لواجهة الصندوق.',
    tooltipDepthBox: 'البعد الجانبي للصندوق.',
    tooltipWidthShoppingBag: 'البعد الأفقي لواجهة الكيس.',
    tooltipHeightShoppingBag: 'البعد العمودي لواجهة الكيس.',
    tooltipGussetShoppingBag: 'عمق اللوحة الجانبية للكيس.',
    tooltipWidthBusinessCard: 'البعد الأفقي للبطاقة.',
    tooltipHeightBusinessCard: 'البعد العمودي للبطاقة.',
    color: 'اللون',
    quantityAndPrice: 'الكمية والسعر',
    quantity: 'الكمية',
    pricePerItem: 'سعر القطعة',
    totalPrice: 'السعر الإجمالي',
    bulkDiscount: 'تم تطبيق خصم الكمية!',
    customSizeQuote: 'اتصل بنا لعرض سعر مخصص',
    addToCart: 'أضف إلى السلة',
    orderNow: 'اطلب الآن وانتقل للدفع',
    itemAddedToCart: 'تمت إضافة المنتج إلى السلة!',
    uploadYourLogoOptional: 'تحميل شعارك (اختياري)',
    uploadLogo: 'تحميل الشعار',
    logoUploadHelpText: 'PNG, JPG, SVG, PDF, PSD, AI بحجم أقصى 2 ميجابايت',
    logoUploaded: 'تم تحميل الشعار',
    removeLogo: 'إزالة الشعار',
    yourDetails: 'معلوماتك',
    description: 'الوصف / ملاحظات',
    descriptionPlaceholder: 'أي تعليمات خاصة أو ملاحظات حول تصميمك...',
    clientName: 'الاسم الكامل',
    phone: 'رقم الهاتف',
    phonePlaceholder: 'مثال: 0512345678',
    wilaya: 'الولاية',
    selectWilaya: 'اختر ولاية',
    commune: 'البلدية',
    selectCommune: 'اختر بلدية',
    address: 'العنوان',
    socialMedia: 'وسائل التواصل الاجتماعي (اختياري)',
    platform: 'المنصة',
    urlPlaceholder: 'https://...',
    url: 'الرابط',
    addSocialLink: 'إضافة رابط تواصل آخر',
    removeSocialLink: 'إزالة رابط التواصل',
    whatsapp: 'واتساب',
    viber: 'فايبر',

    // Cart & Checkout
    emptyCart: 'سلّتك فارغة.',
    proceedToCheckout: 'الانتقال إلى الدفع',
    checkout: 'الدفع',
    orderSummary: 'ملخص الطلب',
    placeOrder: 'تأكيد الطلب',
    
    // Order Tracking
    trackYourOrder: 'تتبع طلبك',
    trackOrderPrompt: 'أدخل معرف طلبك أدناه لمعرفة حالته.',
    enterOrderId: 'أدخل معرف الطلب',
    track: 'تتبع',
    orderNotFound: 'الطلب غير موجود. يرجى التحقق من المعرف والمحاولة مرة أخرى.',
    orderDetails: 'تفاصيل الطلب',
    orderId: 'معرف الطلب',
    submittedOn: 'تاريخ الطلب',
    shippingInfo: 'معلومات الشحن',
    carrier: 'شركة الشحن',
    trackingNumber: 'رقم التتبع',
    products: 'المنتجات',
    status: 'الحالة',
    chatWithUs: 'تواصل معنا',
    typeYourMessage: 'اكتب رسالتك...',
    attachFile: 'إرفاق ملف',
    removeFile: 'إزالة الملف',
    sendMessage: 'إرسال',
    orderPlaced: 'تم استلام الطلب',
    designing: 'مرحلة التصميم',
    printing: 'مرحلة الطباعة',
    packaging: 'مرحلة التغليف',
    shipped: 'تم الشحن',
    completed: 'مكتمل',
    cancelled: 'ملغى',
    pending: 'قيد الانتظار',
    'in production': 'قيد الإنتاج',

    // Thank You & Feedback
    orderSubmittedSuccess: 'تم إرسال طلبك!',
    yourTrackingIdIs: 'معرف التتبع الخاص بك هو:',
    leaveAReview: 'اترك تقييمًا',
    feedbackSubmitted: 'شكراً لك!',
    howWasYourExperience: 'كيف كانت تجربتك مع طلبك؟',
    rating: 'تقييمك',
    comments: 'تعليقات (اختياري)',
    submitFeedback: 'إرسال التقييم',
    reviewAlreadySubmitted: 'لقد قمت بالفعل بإرسال مراجعة لهذا الطلب.',

    // Admin
    manageOrders: 'إدارة الطلبات',
    filterByStatus: 'تصفية حسب الحالة',
    all: 'الكل',
    submittedAt: 'التاريخ',
    actions: 'الإجراءات',
    chat: 'محادثة',
    viewDetails: 'عرض التفاصيل',
    noOrdersFound: 'لم يتم العثور على طلبات لهذه التصفية.',
    ordersSelected: 'تم تحديد {count} طلبات',
    changeStatus: 'تغيير حالة المحدد',
    apply: 'تطبيق',
    deselectAll: 'إلغاء تحديد الكل',
    contactInformation: 'معلومات الاتصال',
    itemWeight: 'وزن السلعة',
    totalWeight: 'الوزن الإجمالي',
    chatWithCustomer: 'محادثة مع العميل',
    shipOrder: 'شحن الطلب',
    deliveryCompany: 'شركة التوصيل',
    markAsShipped: 'تحديد كـ "تم الشحن"',
    creatingShipment: 'جاري إنشاء الشحنة...',
    failedToCreateShipment: 'فشل في إنشاء الشحنة',
    corsErrorExplanation: 'من المحتمل أن يكون هذا خطأ في سياسة CORS لأن هذا تطبيق تجريبي بدون وكيل خلفي. سيتم استخدام رقم تتبع وهمي بدلاً من ذلك.',
    corsErrorTechnicalSolution: 'في تطبيق حقيقي، سيتم حل هذا عن طريق الاتصال بالواجهة الخلفية الخاصة بك، والتي تقوم بعد ذلك بالاتصال بواجهة برمجة تطبيقات التسليم.',
    downloadLogo: 'تحميل شعار العميل',
    editOrder: 'تعديل الطلب',
    saveOrder: 'حفظ الطلب',
    addProduct: 'إضافة منتج',
    removeItem: 'إزالة المنتج',
    confirmRemoveItem: 'هل أنت متأكد من رغبتك في إزالة هذا المنتج من الطلب؟',
    cannotSaveEmptyOrder: 'لا يمكن حفظ طلب بدون منتجات. يرجى إلغاء الطلب بدلاً من ذلك.',
    productEditor: 'محرر المنتجات',
    addNewProduct: 'منتج جديد',
    editProduct: 'تعديل المنتج',
    deleteProduct: 'حذف المنتج',
    confirmDeleteProduct: 'هل أنت متأكد من أنك تريد حذف هذا المنتج وجميع أحجامه المرتبطة به؟',
    productName: 'اسم المنتج',
    productImage: 'صورة المنتج',
    availableColors: 'الألوان المتاحة',
    colorName: 'اسم اللون',
    colorValue: 'قيمة اللون',
    addColor: 'إضافة لون',
    dragToReorder: 'اسحب لإعادة الترتيب',
    sizes: 'الأحجام',
    addNewSize: 'حجم جديد',
    editSize: 'تعديل الحجم',
    deleteSize: 'حذف الحجم',
    confirmDelete: 'هل أنت متأكد؟',
    weightGrams: 'الوزن (جم)',
    pricingTiers: 'مستويات التسعير',
    minQuantity: 'أقل كمية',
    price: 'السعر',
    addTier: 'إضافة مستوى',
    'No sizes configured for this product.': 'لا توجد أحجام مهيأة لهذا المنتج.',
    'to manage its sizes': 'لإدارة أحجامه.',
    formEditor: 'محرر النموذج',
    formEditorDescription: 'تخصيص الحقول والأقسام المرئية للعملاء أثناء تخصيص المنتج.',
    generalSettings: 'الإعدادات العامة',
    logo: 'الشعار',
    homepageContent: 'محتوى الصفحة الرئيسية',
    heroSection: 'قسم الهيرو',
    mainHeadline: 'العنوان الرئيسي',
    subHeadline: 'العنوان الفرعي',
    ctaButtonText: 'نص زر الدعوة للعمل',
    heroImage: 'صورة الهيرو',
    addNewservice: 'خدمة جديدة',
    addNewstep: 'خطوة جديدة',
    addNewtestimonial: 'شهادة جديدة',
    addNewquestion: 'سؤال جديد',
    imageUrl: 'رابط الصورة',
    icon: 'اسم الأيقونة (مثال: select, order, ship)',
    thankYouPageSettings: 'إعدادات صفحة الشكر',
    thankYouTitle: 'عنوان صفحة الشكر',
    thankYouMessage: 'رسالة صفحة الشكر',
    upsellSection: 'قسم البيع الإضافي',
    enableUpsell: 'تفعيل قسم البيع الإضافي',
    upsellTitle: 'عنوان البيع الإضافي',
    productsToShow: 'المنتجات المراد عرضها',
    trackingAndAnalytics: 'التتبع والتحليلات',
    facebookPixelId: 'معرف Facebook Pixel',
    tiktokPixelId: 'معرف TikTok Pixel',
    snapchatPixelId: 'معرف Snapchat Pixel',
    googleAnalyticsId: 'معرف Google Analytics (G-...)',
    footerContent: 'محتوى الفوتر',
    addLink: 'إضافة رابط',
    saved: 'تم الحفظ!',
    toDo: 'قائمة المهام',
    high: 'عالية',
    medium: 'متوسطة',
    low: 'منخفضة',
    priority: 'الأولوية',
    newTaskPlaceholder: 'ما الذي يجب القيام به؟',
    addTask: 'أضف مهمة',
    sortBy: 'فرز حسب',
    sortByPriority: 'الأولوية',
    sortByDate: 'التاريخ',
    noTasks: 'كل شيء على ما يرام! لا توجد مهام هنا.',
    usersAndRoles: 'المستخدمون والأدوار',
    users: 'المستخدمون',
    roles: 'الأدوار',
    permissions: 'الصلاحيات',
    addNewRole: 'إضافة دور جديد',
    editRole: 'تعديل الدور',
    roleName: 'اسم الدور',
    userManagement: 'إدارة المستخدمين',
    roleManagement: 'إدارة الأدوار',
    customers: 'العملاء',
    staff: 'الموظفين',
    role: 'الدور',
    confirmDeleteUser: 'هل أنت متأكد من حذف هذا المستخدم؟ لا يمكن التراجع عن هذا الإجراء.',
    confirmDeleteRole: 'هل أنت متأكد من حذف هذا الدور؟ سيتم إعادة تعيين المستخدمين الذين لديهم هذا الدور إلى دور "عميل".',
    cannotDeleteEssentialRole: 'لا يمكن حذف الدور الأساسي "{roleName}".',


    // Auth
    fullName: 'الاسم الكامل',
    emailAddress: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    myOrders: 'طلباتي',
    orderDate: 'تاريخ الطلب',
    noOrdersYet: 'لم تقم بأي طلبات بعد.',
  },
};

export const AVAILABLE_PERMISSIONS: { [key in Permission]: string } = {
    manage_orders: 'Manage Orders',
    manage_products: 'Manage Products',
    manage_settings: 'Manage Site Settings',
    manage_users_roles: 'Manage Users & Roles',
};

export const SOCIAL_PLATFORMS = [
    { id: 'website', name: 'Website' },
    { id: 'facebook', name: 'Facebook' },
    { id: 'instagram', name: 'Instagram' },
    { id: 'tiktok', name: 'TikTok' },
    { id: 'linkedin', name: 'LinkedIn' },
    { id: 'youtube', name: 'YouTube' },
    { id: 'pinterest', name: 'Pinterest' },
    { id: 'x', name: 'X (Twitter)' },
    { id: 'whatsapp', name: 'WhatsApp' },
    { id: 'viber', name: 'Viber' },
];

export const ORDER_STATUSES: OrderStatus[] = ['Pending', 'Designing', 'Printing', 'In Production', 'Shipped', 'Completed', 'Cancelled'];

export const DELIVERY_COMPANIES: DeliveryCompany[] = [
    {
        id: 'zr-express',
        name: 'ZR Express',
        api: {
            createShipmentUrl: 'https://api.zrexpress.com/create',
            trackShipmentUrl: 'https://api.zrexpress.com/track',
            apiKey: 'ZR-API-KEY-PLACEHOLDER'
        }
    },
    {
        id: 'noest-logistics',
        name: 'NOEST Logistics',
        api: {
            createShipmentUrl: 'https://api.noest.com/shipment',
            trackShipmentUrl: 'https://api.noest.com/tracking',
            apiKey: 'NOEST-API-KEY-PLACEHOLDER'
        }
    },
    {
        id: 'yalidine',
        name: 'Yalidine Express',
    },
    {
        id: 'other',
        name: 'Other (Manual)',
    }
];