
import type { Wilaya } from '../../types.ts';

export const WILAYAS: Wilaya[] = [
  { "id": 1, "name": "Adrar", "baladiyas": [
    { "id": 1, "name": "Adrar" }, { "id": 2, "name": "Tamest" }, { "id": 3, "name": "Charouine" },
    { "id": 4, "name": "Reggane" }, { "id": 5, "name": "In Zghmir" }, { "id": 6, "name": "Tit" },
    { "id": 7, "name": "Ksar Kaddour" }, { "id": 8, "name": "Tsabit" }, { "id": 9, "name": "Timimoun" },
    { "id": 10, "name": "Ouled Said" }, { "id": 11, "name": "Zaouiet Kounta" }, { "id": 12, "name": "Aoulef" },
    { "id": 13, "name": "Tamekten" }, { "id": 14, "name": "Tamantit" }, { "id": 15, "name": "Fenoughil" },
    { "id": 16, "name": "Tinerkouk" }, { "id": 17, "name": "Deldoul" }, { "id": 18, "name": "Sali" },
    { "id": 19, "name": "Akabli" }, { "id": 20, "name": "Metarfa" }, { "id": 21, "name": "Ouled Ahmed Timmi" },
    { "id": 22, "name": "Bouda" }, { "id": 23, "name": "Ouled Aissa" }, { "id": 24, "name": "Talmine" },
    { "id": 25, "name": "Bordj Badji Mokhtar" }, { "id": 26, "name": "Sebaa" }, { "id": 27, "name": "Ouled Brahim" },
    { "id": 28, "name": "Timiaouine" }
  ]},
  { "id": 2, "name": "Chlef", "baladiyas": [
    { "id": 29, "name": "Chlef" }, { "id": 30, "name": "Tenes" }, { "id": 31, "name": "Benairia" },
    { "id": 32, "name": "El Karimia" }, { "id": 33, "name": "Tadjena" }, { "id": 34, "name": "Taougrite" },
    { "id": 35, "name": "Beni Haoua" }, { "id": 36, "name": "Sobha" }, { "id": 37, "name": "Harchoun" },
    { "id": 38, "name": "Ouled Fares" }, { "id": 39, "name": "Sidi Akkacha" }, { "id": 40, "name": "Boukadir" },
    { "id": 41, "name": "Beni Rached" }, { "id": 42, "name": "Talassa" }, { "id": 43, "name": "Herenfa" },
    { "id": 44, "name": "Oued Goussine" }, { "id": 45, "name": "Dahra" }, { "id": 46, "name": "Ouled Abbes" },
    { "id": 47, "name": "Sidi Abderrahmane" }, { "id": 48, "name": "Moussadek" }, { "id": 49, "name": "El Marsa" },
    { "id": 50, "name": "Chettia" }, { "id": 51, "name": "Oued Sly" }, { "id": 52, "name": "Abou El Hassan" },
    { "id": 53, "name": "El Hadjadj" }, { "id": 54, "name": "Labiod Medjadja" }, { "id": 55, "name": "Oum Drou" },
    { "id": 56, "name": "Sendjas" }, { "id": 57, "name": "Zeboudja" }, { "id": 58, "name": "Ouled Ben Abdelkader" },
    { "id": 59, "name": "Bouzeghaia" }, { "id": 60, "name": "Ain Merane" }, { "id": 61, "name": "Oued Fodda" },
    { "id": 62, "name": "Breira" }, { "id": 63, "name": "Beni Bouateb" }
  ]},
  { "id": 3, "name": "Laghouat", "baladiyas": [
    { "id": 64, "name": "Laghouat" }, { "id": 65, "name": "Ksar El Hirane" }, { "id": 66, "name": "Benacer Benchohra" },
    { "id": 67, "name": "Sidi Makhlouf" }, { "id": 68, "name": "Hassi Delaa" }, { "id": 69, "name": "Hassi R'Mel" },
    { "id": 70, "name": "Ain Madhi" }, { "id": 71, "name": "Tadjemout" }, { "id": 72, "name": "Kheneg" },
    { "id": 73, "name": "Gueltat Sidi Saad" }, { "id": 74, "name": "Ain Sidi Ali" }, { "id": 75, "name": "Beidha" },
    { "id": 76, "name": "Brida" }, { "id": 77, "name": "El Ghicha" }, { "id": 78, "name": "Hadj Mechri" },
    { "id": 79, "name": "Sebgag" }, { "id": 80, "name": "Taouiala" }, { "id": 81, "name": "Tadjrouna" },
    { "id": 82, "name": "Aflou" }, { "id": 83, "name": "El Assafia" }, { "id": 84, "name": "Oued Morra" },
    { "id": 85, "name": "Oued M'Zi" }, { "id": 86, "name": "El Houaita" }, { "id": 87, "name": "Sidi Bouzid" }
  ]},
  { "id": 4, "name": "Oum El Bouaghi", "baladiyas": [
    { "id": 88, "name": "Oum El Bouaghi" }, { "id": 89, "name": "Ain Beida" }, { "id": 90, "name": "Ain M'lila" },
    { "id": 91, "name": "Behir Chergui" }, { "id": 92, "name": "El Amiria" }, { "id": 93, "name": "Sigus" },
    { "id": 94, "name": "El Belala" }, { "id": 95, "name": "Ain Babouche" }, { "id": 96, "name": "Berriche" },
    { "id": 97, "name": "Ouled Hamla" }, { "id": 98, "name": "Dhalaa" }, { "id": 99, "name": "Ain Kercha" },
    { "id": 100, "name": "Hanchir Toumghani" }, { "id": 101, "name": "El Djazia" }, { "id": 102, "name": "Ain Diss" },
    { "id": 103, "name": "Fkirina" }, { "id": 104, "name": "Souk Naamane" }, { "id": 105, "name": "Zorg" },
    { "id": 106, "name": "El Fedjoudj Boughrara Saoudi" }, { "id": 107, "name": "Ouled Zouai" }, { "id": 108, "name": "Bir Chouhada" },
    { "id": 109, "name": "Ksar Sbahi" }, { "id": 110, "name": "Oued Nini" }, { "id": 111, "name": "Meskiana" },
    { "id": 112, "name": "Ain Fekroun" }, { "id": 113, "name": "Rahia" }, { "id": 114, "name": "Guettara" },
    { "id": 115, "name": "El Harmilia" }, { "id": 116, "name": "Ouled Gacem" }
  ]},
  { "id": 5, "name": "Batna", "baladiyas": [
    { "id": 117, "name": "Batna" }, { "id": 118, "name": "Ghassira" }, { "id": 119, "name": "Maafa" },
    { "id": 120, "name": "Merouana" }, { "id": 121, "name": "Seriana" }, { "id": 122, "name": "Menaa" },
    { "id": 123, "name": "El Madher" }, { "id": 124, "name": "Tazoult" }, { "id": 125, "name": "N'Gaous" },
    { "id": 126, "name": "Guigba" }, { "id": 127, "name": "Inoughissen" }, { "id": 128, "name": "Arris" },
    { "id": 129, "name": "Ain Djasser" }, { "id": 130, "name": "Ouled Sellam" }, { "id": 131, "name": "Tigherghar" },
    { "id": 132, "name": "Ain Yagout" }, { "id": 133, "name": "Fesdis" }, { "id": 134, "name": "Sefiane" },
    { "id": 135, "name": "Rahbat" }, { "id": 136, "name": "Tighanimine" }, { "id": 137, "name": "Lemsane" },
    { "id": 138, "name": "Ksar Bellezma" }, { "id": 139, "name": "Seggana" }, { "id": 140, "name": "Ichmoul" },
    { "id": 141, "name": "Foum Toub" }, { "id": 142, "name": "Ben Foudhala El Hakania" }, { "id": 143, "name": "Ouyoun El Assafir" },
    { "id": 144, "name": "Djerma" }, { "id": 145, "name": "Bitam" }, { "id": 146, "name": "Metkaouak" },
    { "id": 147, "name": "Barika" }, { "id": 148, "name": "Bouzina" }, { "id": 149, "name": "Chemora" },
    { "id": 150, "name": "Oued Chaaba" }, { "id": 151, "name": "Talkhamt" }, { "id": 152, "name": "Boumaguer" },
    { "id": 153, "name": "Chir" }, { "id": 154, "name": "Teniet El Abed" }, { "id": 155, "name": "Oued Taga" },
    { "id": 156, "name": "Ouled Aouf" }, { "id": 157, "name": "Boumia" }, { "id": 158, "name": "Timgad" },
    { "id": 159, "name": "Ras El Aioun" }, { "id": 160, "name": "Hidoussa" }, { "id": 161, "name": "Kimmel" },
    { "id": 162, "name": "Behir El Chergui" }, { "id": 163, "name": "El Hassi" }, { "id": 164, "name": "Lazrou" },
    { "id": 165, "name": "Bouarif" }, { "id": 166, "name": "Larbaa" }, { "id": 167, "name": "Boulhilat" },
    { "id": 168, "name": "Zanet El Beida" }, { "id": 169, "name": "M'doukel" }, { "id": 170, "name": "Ouled Fadel" },
    { "id": 171, "name": "Taxlent" }, { "id": 172, "name": "Gosbat" }, { "id": 173, "name": "Ouled Ammar" },
    { "id": 174, "name": "Tilatou" }, { "id": 175, "name": "Ain Touta" }, { "id": 176, "name": "Oued El Ma" },
    { "id": 177, "name": "Rassira" }
  ]},
  { "id": 6, "name": "Béjaïa", "baladiyas": [
    { "id": 178, "name": "Bejaia" }, { "id": 179, "name": "Amizour" }, { "id": 180, "name": "Ferraoun" },
    { "id": 181, "name": "Taourirt Ighil" }, { "id": 182, "name": "Chellata" }, { "id": 183, "name": "Tamokra" },
    { "id": 184, "name": "Timezrit" }, { "id": 185, "name": "Souk El Tenine" }, { "id": 186, "name": "M'cisna" },
    { "id": 187, "name": "Tinabdher" }, { "id": 188, "name": "Tichy" }, { "id": 189, "name": "Semaoun" },
    { "id": 190, "name": "Kendira" }, { "id": 191, "name": "Tifra" }, { "id": 192, "name": "Ighram" },
    { "id": 193, "name": "Amalou" }, { "id": 194, "name": "Ighil Ali" }, { "id": 195, "name": "Fenaia Il Maten" },
    { "id": 196, "name": "Toudja" }, { "id": 197, "name": "Darguina" }, { "id": 198, "name": "Sidi Ayad" },
    { "id": 199, "name": "Aokas" }, { "id": 200, "name": "Beni Djellil" }, { "id": 201, "name": "Adekar" },
    { "id": 202, "name": "Akbou" }, { "id": 203, "name": "Seddouk" }, { "id": 204, "name": "Tazmalt" },
    { "id": 205, "name": "Ait R'zine" }, { "id": 206, "name": "Chemini" }, { "id": 207, "name": "Souk Oufella" },
    { "id": 208, "name": "Tibane" }, { "id": 209, "name": "Tala Hamza" }, { "id": 210, "name": "Barbacha" },
    { "id": 211, "name": "Beni Ksila" }, { "id": 212, "name": "Ouzellaguen" }, { "id": 213, "name": "Bouhamza" },
    { "id": 214, "name": "Beni Melikeche" }, { "id": 215, "name": "Sidi Aich" }, { "id": 216, "name": "El Kseur" },
    { "id": 217, "name": "Melbou" }, { "id": 218, "name": "Akfadou" }, { "id": 219, "name": "Leflaye" },
    { "id": 220, "name": "Kherrata" }, { "id": 221, "name": "Dra El Caid" }, { "id": 222, "name": "Tamridjet" },
    { "id": 223, "name": "Ait Smail" }, { "id": 224, "name": "Boukhelifa" }, { "id": 225, "name": "Tizi N'Berber" },
    { "id": 226, "name": "Beni Maouche" }, { "id": 227, "name": "Oued Ghir" }, { "id": 228, "name": "Taskriout" },
    { "id": 229, "name": "Ait Melloul" }
  ]},
  { "id": 7, "name": "Biskra", "baladiyas": [
    { "id": 230, "name": "Biskra" }, { "id": 231, "name": "Oumache" }, { "id": 232, "name": "Branis" },
    { "id": 233, "name": "Chetma" }, { "id": 234, "name": "El Hadjab" }, { "id": 235, "name": "Sidi Okba" },
    { "id": 236, "name": "M'chouneche" }, { "id": 237, "name": "El Haouch" }, { "id": 238, "name": "Ain Naga" },
    { "id": 239, "name": "Zeribet El Oued" }, { "id": 240, "name": "El Mizaraa" }, { "id": 241, "name": "Foughala" },
    { "id": 242, "name": "Djemorah" }, { "id": 243, "name": "Tolga" }, { "id": 244, "name": "Bordj Ben Azzouz" },
    { "id": 245, "name": "Lichana" }, { "id": 246, "name": "El Outaya" }, { "id": 247, "name": "Bouchagroune" },
    { "id": 248, "name": "Mekhadma" }, { "id": 249, "name": "El Feidh" }, { "id": 250, "name": "Khenguet Sidi Nadji" },
    { "id": 251, "name": "Ouled Djellal" }, { "id": 252, "name": "Doucen" }, { "id": 253, "name": "Chaatet" },
    { "id": 254, "name": "Besbes" }, { "id": 255, "name": "Sidi Khaled" }, { "id": 256, "name": "Ras El Miaad" },
    { "id": 257, "name": "El Ghrous" }, { "id": 258, "name": "El Kantara" }, { "id": 259, "name": "Ain Zaatout" },
    { "id": 260, "name": "Lioua" }, { "id": 261, "name": "M'lili" }, { "id": 262, "name": "Ourlal" }
  ]},
  { "id": 8, "name": "Béchar", "baladiyas": [
    { "id": 263, "name": "Bechar" }, { "id": 264, "name": "Erg Ferradj" }, { "id": 265, "name": "Ouled Khoudir" },
    { "id": 266, "name": "Meridja" }, { "id": 267, "name": "Timoudi" }, { "id": 268, "name": "Lahmar" },
    { "id": 269, "name": "Beni Abbes" }, { "id": 270, "name": "Beni Ikhlef" }, { "id": 271, "name": "Mechraa Houari Boumediene" },
    { "id": 272, "name": "Kenadsa" }, { "id": 273, "name": "Igli" }, { "id": 274, "name": "Tabelbala" },
    { "id": 275, "name": "Taghit" }, { "id": 276, "name": "El Ouata" }, { "id": 277, "name": "Boukais" },
    { "id": 278, "name": "Mogheul" }, { "id": 279, "name": "Abadla" }, { "id": 280, "name": "Kerzaz" },
    { "id": 281, "name": "Ksabi" }, { "id": 282, "name": "Tamtert" }, { "id": 283, "name": "Beni Ounif" }
  ]},
  { "id": 9, "name": "Blida", "baladiyas": [
    { "id": 284, "name": "Blida" }, { "id": 285, "name": "Chebli" }, { "id": 286, "name": "Bouinan" },
    { "id": 287, "name": "Oued Alleug" }, { "id": 288, "name": "Ouled Yaich" }, { "id": 289, "name": "Chrea" },
    { "id": 290, "name": "El Affroun" }, { "id": 291, "name": "Chiffa" }, { "id": 292, "name": "Hammam Melouane" },
    { "id": 293, "name": "Benkhelil" }, { "id": 294, "name": "Souma" }, { "id": 295, "name": "Mouzaia" },
    { "id": 296, "name": "Souhane" }, { "id": 297, "name": "Meftah" }, { "id": 298, "name": "Ouled Slama" },
    { "id": 299, "name": "Bouarfa" }, { "id": 300, "name": "Beni Tamou" }, { "id": 301, "name": "Bougara" },
    { "id": 302, "name": "Guerrouaou" }, { "id": 303, "name": "Larbaa" }, { "id": 304, "name": "Beni Mered" },
    { "id": 305, "name": "Ain Romana" }, { "id": 306, "name": "Djebabra" }, { "id": 307, "name": "Oued Djer" },
    { "id": 308, "name": "Tamesguida" }
  ]},
  { "id": 10, "name": "Bouira", "baladiyas": [
    { "id": 309, "name": "Bouira" }, { "id": 310, "name": "El Asnam" }, { "id": 311, "name": "Guerrouma" },
    { "id": 312, "name": "Souk El Khemis" }, { "id": 313, "name": "Aomar" }, { "id": 314, "name": "Chorfa" },
    { "id": 315, "name": "Hanif" }, { "id": 316, "name": "Ouled Rached" }, { "id": 317, "name": "Ain Laloui" },
    { "id": 318, "name": "Hadjera Zerga" }, { "id": 319, "name": "Mezdour" }, { "id": 320, "name": "Haizer" },
    { "id": 321, "name": "Lakhdaria" }, { "id": 322, "name": "Maala" }, { "id": 323, "name": "El Mokrani" },
    { "id": 324, "name": "Ain El Hadjar" }, { "id": 325, "name": "Aghbalou" }, { "id": 326, "name": "Taghzout" },
    { "id": 327, "name": "Raouraoua" }, { "id": 328, "name": "El Adjiba" }, { "id": 329, "name": "Dechmia" },
    { "id": 330, "name": "Ridane" }, { "id": 331, "name": "Bechloul" }, { "id": 332, "name": "Bouderbala" },
    { "id": 333, "name": "El Khabouzia" }, { "id": 334, "name": "Ain Turk" }, { "id": 335, "name": "Saharidj" },
    { "id": 336, "name": "M'chedallah" }, { "id": 337, "name": "Dirah" }, { "id": 338, "name": "El Hachimia" },
    { "id": 339, "name": "Maamora" }, { "id": 340, "name": "Kadiria" }, { "id": 341, "name": "Djebahia" },
    { "id": 342, "name": "Bir Ghbalou" }, { "id": 343, "name": "Taguedit" }, { "id": 344, "name": "Ath Mansour" },
    { "id": 345, "name": "Ait Laaziz" }, { "id": 346, "name": "Boukram" }, { "id": 347, "name": "Sour El Ghozlane" },
    { "id": 348, "name": "Z'barbar" }, { "id": 349, "name": "Oued El Berdi" }, { "id": 350, "name": "El Hakimia" },
    { "id": 351, "name": "Ain Bessam" }, { "id": 352, "name": "El Mesdour" }, { "id": 353, "name": "El Bouna" }
  ]},
  { "id": 11, "name": "Tamanrasset", "baladiyas": [
    { "id": 354, "name": "Tamanrasset" }, { "id": 355, "name": "Ain Amguel" }, { "id": 356, "name": "Idles" },
    { "id": 357, "name": "Abelsa" }, { "id": 358, "name": "Tazrouk" }, { "id": 359, "name": "Ain Salah" },
    { "id": 360, "name": "Ain Guezzam" }, { "id": 361, "name": "Foggaret Ezzaouia" }, { "id": 362, "name": "Tin Zaouatine" },
    { "id": 363, "name": "Inghar" }
  ]},
  { "id": 12, "name": "Tébessa", "baladiyas": [
    { "id": 364, "name": "Tebessa" }, { "id": 365, "name": "Bir El Ater" }, { "id": 366, "name": "Cheria" },
    { "id": 367, "name": "Stah Guentis" }, { "id": 368, "name": "El Aouinet" }, { "id": 369, "name": "El Houidjbet" },
    { "id": 370, "name": "Safsaf El Ouesra" }, { "id": 371, "name": "Hammamet" }, { "id": 372, "name": "Negrine" },
    { "id": 373, "name": "Bir Mokkadem" }, { "id": 374, "name": "El Kouif" }, { "id": 375, "name": "Morsott" },
    { "id": 376, "name": "Telidjene" }, { "id": 377, "name": "Ain Zerga" }, { "id": 378, "name": "Ouenza" },
    { "id": 379, "name": "El Ma Labiodh" }, { "id": 380, "name": "Oum Ali" }, { "id": 381, "name": "Tlidjene" },
    { "id": 382, "name": "El Ogla" }, { "id": 383, "name": "Bekkaria" }, { "id": 384, "name": "Boulhaf Dyr" },
    { "id": 385, "name": "El Mezeraa" }, { "id": 386, "name": "Boukhadra" }, { "id": 387, "name": "Guorriguer" },
    { "id": 388, "name": "Bir Dheb" }, { "id": 389, "name": "Ogla Melha" }, { "id": 390, "name": "Ferkane" },
    { "id": 391, "name": "El Malabiod" }
  ]},
  { "id": 13, "name": "Tlemcen", "baladiyas": [
    { "id": 392, "name": "Tlemcen" }, { "id": 393, "name": "Beni Mester" }, { "id": 394, "name": "Ain Tallout" },
    { "id": 395, "name": "Remchi" }, { "id": 396, "name": "El Fehoul" }, { "id": 397, "name": "Sabra" },
    { "id": 398, "name": "Ghazaouet" }, { "id": 399, "name": "Souani" }, { "id": 400, "name": "Djebala" },
    { "id": 401, "name": "El Gor" }, { "id": 402, "name": "Oued Chouly" }, { "id": 403, "name": "Ain Fetah" },
    { "id": 404, "name": "Ain Ghoraba" }, { "id": 405, "name": "Chetouane" }, { "id": 406, "name": "Mansourah" },
    { "id": 407, "name": "Beni Snous" }, { "id": 408, "name": "Azails" }, { "id": 409, "name": "Sebdou" },
    { "id": 410, "name": "Beni Bahdel" }, { "id": 411, "name": "Beni Khellad" }, { "id": 412, "name": "Honnaine" },
    { "id": 413, "name": "Beni Ouarsous" }, { "id": 414, "name": "Sidi Djillali" }, { "id": 415, "name": "Bouhlou" },
    { "id": 416, "name": "Maghnia" }, { "id": 417, "name": "Hammam Boughrara" }, { "id": 418, "name": "Souk Tleta" },
    { "id": 419, "name": "Ain Fares" }, { "id": 420, "name": "Sidi Medjahed" }, { "id": 421, "name": "Bensekrane" },
    { "id": 422, "name": "Ain Kebira" }, { "id": 423, "name": "Ain Youcef" }, { "id": 424, "name": "Zenata" },
    { "id": 425, "name": "Ouled Riyah" }, { "id": 426, "name": "Bouihi" }, { "id": 427, "name": "Hennaya" },
    { "id": 428, "name": "Ouled Mimoun" }, { "id": 429, "name": "Amieur" }, { "id": 430, "name": "Ain Fezza" },
    { "id": 431, "name": "Fellaoucene" }, { "id": 432, "name": "Sidi Abdelli" }, { "id": 433, "name": "Souk El Khemis" },
    { "id": 434, "name": "Dar Yaghmouracene" }, { "id": 435, "name": "Terny Beni Hediel" }, { "id": 436, "name": "Marsa Ben M'hidi" },
    { "id": 437, "name": "Sidi Kacem" }, { "id": 438, "name": "Souahlia" }, { "id": 439, "name": "Tianet" },
    { "id": 440, "name": "Nedroma" }, { "id": 441, "name": "Beni Smiel" }, { "id": 442, "name": "El Aricha" },
    { "id": 443, "name": "Bab El Assa" }, { "id": 444, "name": "MSirda Fouaga" }
  ]},
  { "id": 14, "name": "Tiaret", "baladiyas": [
    { "id": 445, "name": "Tiaret" }, { "id": 446, "name": "Medroussa" }, { "id": 447, "name": "Ain Deheb" },
    { "id": 448, "name": "Chehaima" }, { "id": 449, "name": "Rechaiga" }, { "id": 450, "name": "Mellakou" },
    { "id": 451, "name": "Sebaine" }, { "id": 452, "name": "Tousnina" }, { "id": 453, "name": "Meghila" },
    { "id": 454, "name": "Sebt" }, { "id": 455, "name": "Sidi Hosni" }, { "id": 456, "name": "Ain El Hadid" },
    { "id": 457, "name": "Frenda" }, { "id": 458, "name": "Ain Kermes" }, { "id": 459, "name": "Ksar Chellala" },
    { "id": 460, "name": "Guertoufa" }, { "id": 461, "name": "Serghine" }, { "id": 462, "name": "Zmalet El Emir Abdelkader" },
    { "id": 463, "name": "Madna" }, { "id": 464, "name": "Sougueur" }, { "id": 465, "name": "Faidja" },
    { "id": 466, "name": "Si Abdelghani" }, { "id": 467, "name": "Ain Bouchekif" }, { "id": 468, "name": "Dahmouni" },
    { "id": 469, "name": "Rahouia" }, { "id": 470, "name": "Mahdia" }, { "id": 471, "name": "Ain Dzarit" },
    { "id": 472, "name": "Sidi Ali Mellal" }, { "id": 473, "name": "Nadorah" }, { "id": 474, "name": "Tagdempt" },
    { "id": 475, "name": "Oued Lilli" }, { "id": 476, "name": "Sidi Bakhti" }, { "id": 477, "name": "Mechraa Safa" },
    { "id": 478, "name": "Djillali Ben Amar" }, { "id": 479, "name": "Sidi Abderrahmane" }, { "id": 480, "name": "Medrissa" },
    { "id": 481, "name": "Faidja" }, { "id": 482, "name": "Takhemaret" }, { "id": 483, "name": "Sidi Ameur" },
    { "id": 484, "name": "Naima" }, { "id": 485, "name": "Ain Beida" }, { "id": 486, "name": "Ouanougha" }
  ]},
  { "id": 15, "name": "Tizi Ouzou", "baladiyas": [
    { "id": 487, "name": "Tizi Ouzou" }, { "id": 488, "name": "Ain El Hammam" }, { "id": 489, "name": "Akbil" },
    { "id": 490, "name": "Freha" }, { "id": 491, "name": "Souamaa" }, { "id": 492, "name": "Mechtras" },
    { "id": 493, "name": "Irdjen" }, { "id": 494, "name": "Timizart" }, { "id": 495, "name": "Makouda" },
    { "id": 496, "name": "Dra" }, { "id": 497, "name": "Beni Aissi" }, { "id": 498, "name": "Beni Zikki" },
    { "id": 499, "name": "Boudjima" }, { "id": 500, "name": "Ain Zaouia" }, { "id": 501, "name": "Azzefoun" },
    { "id": 502, "name": "Tigzirt" }, { "id": 503, "name": "Beni Douala" }, { "id": 504, "name": "Ouaguenoun" },
    { "id": 505, "name": "Ifigha" }, { "id": 506, "name": "Ait Yahia" }, { "id": 507, "name": "Tizi Gheniff" },
    { "id": 508, "name": "Iferhounene" }, { "id": 509, "name": "Mekla" }, { "id": 510, "name": "Tizi N'Tleta" },
    { "id": 511, "name": "Beni Zmenzer" }, { "id": 512, "name": "Iflissen" }, { "id": 513, "name": "Beni Yenni" },
    { "id": 514, "name": "Azazga" }, { "id": 515, "name": "Aghribs" }, { "id": 516, "name": "Boghni" },
    { "id": 517, "name": "Tirmitine" }, { "id": 518, "name": "Ait Khellili" }, { "id": 519, "name": "Sidi Naamane" },
    { "id": 520, "name": "Iboudrarene" }, { "id": 521, "name": "Ait Chafaa" }, { "id": 522, "name": "Akerrou" },
    { "id": 523, "name": "Yatafene" }, { "id": 524, "name": "Ait Oumalou" }, { "id": 525, "name": "Yakourene" },
    { "id": 526, "name": "Larbaa Nath Irathen" }, { "id": 527, "name": "Zekri" }, { "id": 528, "name": "Ouacif" },
    { "id": 529, "name": "Ait Bouaddou" }, { "id": 530, "name": "Abi Youcef" }, { "id": 531, "name": "Beni Ourtilane" },
    { "id": 532, "name": "M'kira" }, { "id": 533, "name": "Bounouh" }, { "id": 534, "name": "Draa Ben Khedda" },
    { "id": 535, "name": "Assi Youcef" }, { "id": 536, "name": "Tadmait" }, { "id": 537, "name": "Ait Mahmoud" },
    { "id": 538, "name": "Idjeur" }, { "id": 539, "name": "Maatkas" }, { "id": 540, "name": "Ait Yahia Moussa" },
    { "id": 541, "name": "Souk El Thenine" }, { "id": 542, "name": "Ait Toudert" }, { "id": 543, "name": "Tizi Rached" },
    { "id": 544, "name": "Illilten" }, { "id": 545, "name": "Ouadhia" }, { "id": 546, "name": "Ait Aggouacha" },
    { "id": 547, "name": "Ait Boumahdi" }, { "id": 548, "name": "Agouni Gueghrane" }, { "id": 549, "name": "Ait Aissa Mimoun" },
    { "id": 550, "name": "Beni Amrane" }, { "id": 551, "name": "Illoula Oumalou" }, { "id": 552, "name": "Imsouhal" },
    { "id": 553, "name": "Sidi M'Hamed" }
  ]},
  { "id": 16, "name": "Alger", "baladiyas": [
    { "id": 554, "name": "Alger Centre" }, { "id": 555, "name": "Sidi M'Hamed" }, { "id": 556, "name": "El Madania" },
    { "id": 557, "name": "Hamma-Anassers" }, { "id": 558, "name": "Bab El Oued" }, { "id": 559, "name": "Bologhine" },
    { "id": 560, "name": "Casbah" }, { "id": 561, "name": "Oued Koriche" }, { "id": 562, "name": "Bir Mourad Rais" },
    { "id": 563, "name": "El Biar" }, { "id": 564, "name": "Bouzareah" }, { "id": 565, "name": "Birkhadem" },
    { "id": 566, "name": "El Harrach" }, { "id": 567, "name": "Baraki" }, { "id": 568, "name": "Oued Smar" },
    { "id": 569, "name": "Bachdjerrah" }, { "id": 570, "name": "Hussein Dey" }, { "id": 571, "name": "Kouba" },
    { "id": 572, "name": "Bourouba" }, { "id": 573, "name": "Dar El Beida" }, { "id": 574, "name": "Bab Ezzouar" },
    { "id": 575, "name": "Ben Aknoun" }, { "id": 576, "name": "Dely Ibrahim" }, { "id": 577, "name": "El Hammamet" },
    { "id": 578, "name": "Rais Hamidou" }, { "id": 579, "name": "Djasr Kasentina" }, { "id": 580, "name": "El Mouradia" },
    { "id": 581, "name": "Hydra" }, { "id": 582, "name": "Mohammadia" }, { "id": 583, "name": "Bordj El Kiffan" },
    { "id": 584, "name": "El Magharia" }, { "id": 585, "name": "Beni Messous" }, { "id": 586, "name": "Les Eucalyptus" },
    { "id": 587, "name": "Bordj El Bahri" }, { "id": 588, "name": "El Marsa" }, { "id": 589, "name": "Cheraga" },
    { "id": 590, "name": "Ouled Chebel" }, { "id": 591, "name": "Tessala El Merdja" }, { "id": 592, "name": "Ain Taya" },
    { "id": 593, "name": "Herraoua" }, { "id": 594, "name": "Reghaia" }, { "id": 595, "name": "Rouiba" },
    { "id": 596, "name": "Staoueli" }, { "id": 597, "name": "Souidania" }, { "id": 598, "name": "Zeralda" },
    { "id": 599, "name": "Mahelma" }, { "id": 600, "name": "Rahmania" }, { "id": 601, "name": "Douera" },
    { "id": 602, "name": "Draria" }, { "id": 603, "name": "El Achour" }, { "id": 604, "name": "Baba Hassen" },
    { "id": 605, "name": "Khraicia" }, { "id": 606, "name": "Saoula" }, { "id": 607, "name": "Ain Benian" },
    { "id": 608, "name": "Ouled Fayet" }, { "id": 609, "name": "Sidi Moussa" }, { "id": 610, "name": "Sebala" }
  ]},
  { "id": 17, "name": "Djelfa", "baladiyas": [
    { "id": 611, "name": "Djelfa" }, { "id": 612, "name": "Messaad" }, { "id": 613, "name": "Charef" },
    { "id": 614, "name": "Benyagoub" }, { "id": 615, "name": "El Guedid" }, { "id": 616, "name": "Had Sahary" },
    { "id": 617, "name": "Sidi Baizid" }, { "id": 618, "name": "Faidh El Botma" }, { "id": 619, "name": "Ain El Ibel" },
    { "id": 620, "name": "Moudjebara" }, { "id": 621, "name": "Tadmit" }, { "id": 622, "name": "Zaafrane" },
    { "id": 623, "name": "Hassi Bahbah" }, { "id": 624, "name": "Zaccar" }, { "id": 625, "name": "El Khemis" },
    { "id": 626, "name": "Sed Rahal" }, { "id": 627, "name": "Selmana" }, { "id": 628, "name": "Ain Fekka" },
    { "id": 629, "name": "Bouira Lahdab" }, { "id": 630, "name": "Sidi Ladjel" }, { "id": 631, "name": "Hassi El Euch" },
    { "id": 632, "name": "El Oussara" }, { "id": 633, "name": "Guernini" }, { "id": 634, "name": "Birine" },
    { "id": 635, "name": "Oum Laadham" }, { "id": 636, "name": "Dar Chioukh" }, { "id": 637, "name": "Mliliha" },
    { "id": 638, "name": "Ain Maabed" }, { "id": 639, "name": "Guettara" }, { "id": 640, "name": "Deldoul" },
    { "id": 641, "name": "Douis" }, { "id": 642, "name": "Benhar" }, { "id": 643, "name": "Amourah" },
    { "id": 644, "name": "Zarzour" }, { "id": 645, "name": "Ain Oussera" }, { "id": 646, "name": "El Idrissia" }
  ]},
  { "id": 18, "name": "Jijel", "baladiyas": [
    { "id": 647, "name": "Jijel" }, { "id": 648, "name": "Eraguene" }, { "id": 649, "name": "El Aouana" },
    { "id": 650, "name": "Ziama Mansouriah" }, { "id": 651, "name": "Taher" }, { "id": 652, "name": "Emir Abdelkader" },
    { "id": 653, "name": "Chekfa" }, { "id": 654, "name": "Chahna" }, { "id": 655, "name": "El Milia" },
    { "id": 656, "name": "Sidi Maarouf" }, { "id": 657, "name": "Settara" }, { "id": 658, "name": "El Ancer" },
    { "id": 659, "name": "Sidi Abdelaziz" }, { "id": 660, "name": "Kaous" }, { "id": 661, "name": "Ghebala" },
    { "id": 662, "name": "Bouraoui Belhadef" }, { "id": 663, "name": "Texenna" }, { "id": 664, "name": "Djemaa Beni Habibi" },
    { "id": 665, "name": "Bordj Tahar" }, { "id": 666, "name": "Ouled Yahia Khedrouche" }, { "id": 667, "name": "Boucif Ouled Askeur" },
    { "id": 668, "name": "Selma Benziada" }, { "id": 669, "name": "Ouled Rabah" }, { "id": 670, "name": "Kennar Nouchfi" },
    { "id": 671, "name": "Ouadjana" }, { "id": 672, "name": "El Kennar" }, { "id": 673, "name": "Sidi M'Hamed Benali" },
    { "id": 674, "name": "Boussif Ouled Askeur" }
  ]},
  { "id": 19, "name": "Sétif", "baladiyas": [
    { "id": 675, "name": "Setif" }, { "id": 676, "name": "Ain El Kebira" }, { "id": 677, "name": "Beni Aziz" },
    { "id": 678, "name": "Ouled Si Ahmed" }, { "id": 679, "name": "Boutaleb" }, { "id": 680, "name": "Hammam Guergour" },
    { "id": 681, "name": "Ain Roua" }, { "id": 682, "name": "Draa Kebila" }, { "id": 683, "name": "Beni Ourtilane" },
    { "id": 684, "name": "Ain Lahdjar" }, { "id": 685, "name": "Ain Abessa" }, { "id": 686, "name": "Dehamcha" },
    { "id": 687, "name": "Babor" }, { "id": 688, "name": "Guidjel" }, { "id": 689, "name": "Ain Oulmene" },
    { "id": 690, "name": "El Eulma" }, { "id": 691, "name": "Djemila" }, { "id": 692, "name": "Ain Arnat" },
    { "id": 693, "name": "Amoucha" }, { "id": 694, "name": "Salah Bey" }, { "id": 695, "name": "Ain Azel" },
    { "id": 696, "name": "Guenzet" }, { "id": 697, "name": "Harbil" }, { "id": 698, "name": "Bouandas" },
    { "id": 699, "name": "Hamma" }, { "id": 700, "name": "Maaouia" }, { "id": 701, "name": "Rosfa" },
    { "id": 702, "name": "Talaifacene" }, { "id": 703, "name": "Beni Fouda" }, { "id": 704, "name": "Tachouda" },
    { "id": 705, "name": "Bougaa" }, { "id": 706, "name": "Ain Sebt" }, { "id": 707, "name": "Beni Chebana" },
    { "id": 708, "name": "Bazer Sakhra" }, { "id": 709, "name": "Mezloug" }, { "id": 710, "name": "Ain Legradj" },
    { "id": 711, "name": "Ksar El Abtal" }, { "id": 712, "name": "Ouled Tebben" }, { "id": 713, "name": "Hammam Soukhna" },
    { "id": 714, "name": "Taya" }, { "id": 715, "name": "Bir El Arch" }, { "id": 716, "name": "Serdj El Ghoul" },
    { "id": 717, "name": "Beidha Bordj" }, { "id": 718, "name": "Tella" }, { "id": 719, "name": "Beni Mouhli" },
    { "id": 720, "name": "Ouled Addouane" }, { "id": 721, "name": "Ouled Sabor" }, { "id": 722, "name": "Guellal" },
    { "id": 723, "name": "Kasr El Abtal" }, { "id": 724, "name": "El Ouldja" }, { "id": 725, "name": "Bir Haddada" },
    { "id": 726, "name": "Rasfa" }, { "id": 727, "name": "Oued El Bared" }, { "id": 728, "name": "El Ouricia" },
    { "id": 729, "name": "Tizi N'Bechar" }, { "id": 730, "name": "Ait Naoual Mezada" }, { "id": 731, "name": "Ait Tizi" },
    { "id": 732, "name": "Beni Hocine" }, { "id": 733, "name": "Guedjel" }, { "id": 734, "name": "Guelta Zerka" }
  ]},
  { "id": 20, "name": "Saïda", "baladiyas": [
    { "id": 735, "name": "Saida" }, { "id": 736, "name": "Ouled Khaled" }, { "id": 737, "name": "Ain El Hadjar" },
    { "id": 738, "name": "Moulay Larbi" }, { "id": 739, "name": "Youb" }, { "id": 740, "name": "Doui Thabet" },
    { "id": 741, "name": "Hounet" }, { "id": 742, "name": "Sidi Amar" }, { "id": 743, "name": "Sidi Boubekeur" },
    { "id": 744, "name": "Ouled Brahim" }, { "id": 745, "name": "Tircine" }, { "id": 746, "name": "Maamora" },
    { "id": 747, "name": "El Hassasna" }, { "id": 748, "name": "Ain Sekhouna" }, { "id": 749, "name": "Ain Soltane" },
    { "id": 750, "name": "Sidi Ahmed" }
  ]},
  { "id": 21, "name": "Skikda", "baladiyas": [
    { "id": 751, "name": "Skikda" }, { "id": 752, "name": "Ain Zouit" }, { "id": 753, "name": "El Hadaiek" },
    { "id": 754, "name": "Bouchetata" }, { "id": 755, "name": "Oum Toub" }, { "id": 756, "name": "Beni Oulbane" },
    { "id": 757, "name": "Kerkera" }, { "id": 758, "name": "El Ghedir" }, { "id": 759, "name": "Ain Kechra" },
    { "id": 760, "name": "Ouldja Boulballout" }, { "id": 761, "name": "Ramdane Djamel" }, { "id": 762, "name": "Beni Bechir" },
    { "id": 763, "name": "Sidi Mezghiche" }, { "id": 764, "name": "Emdjez Edchich" }, { "id": 765, "name": "Tamalous" },
    { "id": 766, "name": "Bin El Ouiden" }, { "id": 767, "name": "Zerdazas" }, { "id": 768, "name": "Ouled Hbaba" },
    { "id": 769, "name": "Es Sebt" }, { "id": 770, "name": "Azzaba" }, { "id": 771, "name