
import type { Wilaya } from './types';

export const WILAYAS: Wilaya[] = [
  { "id": 1, "name": "Adrar", "baladiyas": [
    { "id": 1, "name": "Adrar" }, { "id": 2, "name": "Tamest" }, { "id": 3, "name": "Charouine" },
    { "id": 4, "name": "Reggane" }, { "id": 5, "name": "In Zghmir" }, { "id": 6, "name": "Tit" },
    { "id": 7, "name": "Ksar Kaddour" }, { "id": 8, "name": "Tsabit" }, { "id": 9, "name": "Timimoun" },
    { "id": 10, "name": "Ouled Said" }, { "id": 11, "name": "Zaouiet Kounta" }, { "id": 12, "name": "Aoulef" },
    { "id": 13, "name": "Tamekten" }, { "id": 14, "name": "Tamantit" }, { "id": 15, "name": "Fenoughil" },
    { "id": 16, "name": "Tinerkouk" }, { "id": 17, "name": "Deldoul" }, { "id": 18, "name": "Sali" },
    { "id": 19, "name": "Akabli" }, { "id": 20, "name": "Metarfa" }, { "id": 21, "name": "Ouled Ahmed Timmi" },
    { "id": 22, "name": "Bouda" }, { "id": 23, "name": "Ouled Aissa" }, { "id": 24, "name": "Talmine" },
    { "id": 25, "name": "Bordj Badji Mokhtar" }, { "id": 26, "name": "Sebaa" }, { "id": 27, "name": "Ouled Brahim" },
    { "id": 28, "name": "Timiaouine" }
  ]},
  { "id": 2, "name": "Chlef", "baladiyas": [
    { "id": 29, "name": "Chlef" }, { "id": 30, "name": "Tenes" }, { "id": 31, "name": "Benairia" },
    { "id": 32, "name": "El Karimia" }, { "id": 33, "name": "Tadjena" }, { "id": 34, "name": "Taougrite" },
    { "id": 35, "name": "Beni Haoua" }, { "id": 36, "name": "Sobha" }, { "id": 37, "name": "Harchoun" },
    { "id": 38, "name": "Ouled Fares" }, { "id": 39, "name": "Sidi Akkacha" }, { "id": 40, "name": "Boukadir" },
    { "id": 41, "name": "Beni Rached" }, { "id": 42, "name": "Talassa" }, { "id": 43, "name": "Herenfa" },
    { "id": 44, "name": "Oued Goussine" }, { "id": 45, "name": "Dahra" }, { "id": 46, "name": "Ouled Abbes" },
    { "id": 47, "name": "Sidi Abderrahmane" }, { "id": 48, "name": "Moussadek" }, { "id": 49, "name": "El Marsa" },
    { "id": 50, "name": "Chettia" }, { "id": 51, "name": "Oued Sly" }, { "id": 52, "name": "Abou El Hassan" },
    { "id": 53, "name": "El Hadjadj" }, { "id": 54, "name": "Labiod Medjadja" }, { "id": 55, "name": "Oum Drou" },
    { "id": 56, "name": "Sendjas" }, { "id": 57, "name": "Zeboudja" }, { "id": 58, "name": "Ouled Ben Abdelkader" },
    { "id": 59, "name": "Bouzeghaia" }, { "id": 60, "name": "Ain Merane" }, { "id": 61, "name": "Oued Fodda" },
    { "id": 62, "name": "Breira" }, { "id": 63, "name": "Beni Bouateb" }
  ]},
  { "id": 3, "name": "Laghouat", "baladiyas": [
    { "id": 64, "name": "Laghouat" }, { "id": 65, "name": "Ksar El Hirane" }, { "id": 66, "name": "Benacer Benchohra" },
    { "id": 67, "name": "Sidi Makhlouf" }, { "id": 68, "name": "Hassi Delaa" }, { "id": 69, "name": "Hassi R'Mel" },
    { "id": 70, "name": "Ain Madhi" }, { "id": 71, "name": "Tadjemout" }, { "id": 72, "name": "Kheneg" },
    { "id": 73, "name": "Gueltat Sidi Saad" }, { "id": 74, "name": "Ain Sidi Ali" }, { "id": 75, "name": "Beidha" },
    { "id": 76, "name": "Brida" }, { "id": 77, "name": "El Ghicha" }, { "id": 78, "name": "Hadj Mechri" },
    { "id": 79, "name": "Sebgag" }, { "id": 80, "name": "Taouiala" }, { "id": 81, "name": "Tadjrouna" },
    { "id": 82, "name": "Aflou" }, { "id": 83, "name": "El Assafia" }, { "id": 84, "name": "Oued Morra" },
    { "id": 85, "name": "Oued M'Zi" }, { "id": 86, "name": "El Houaita" }, { "id": 87, "name": "Sidi Bouzid" }
  ]},
  { "id": 4, "name": "Oum El Bouaghi", "baladiyas": [
    { "id": 88, "name": "Oum El Bouaghi" }, { "id": 89, "name": "Ain Beida" }, { "id": 90, "name": "Ain M'lila" },
    { "id": 91, "name": "Behir Chergui" }, { "id": 92, "name": "El Amiria" }, { "id": 93, "name": "Sigus" },
    { "id": 94, "name": "El Belala" }, { "id": 95, "name": "Ain Babouche" }, { "id": 96, "name": "Berriche" },
    { "id": 97, "name": "Ouled Hamla" }, { "id": 98, "name": "Dhalaa" }, { "id": 99, "name": "Ain Kercha" },
    { "id": 100, "name": "Hanchir Toumghani" }, { "id": 101, "name": "El Djazia" }, { "id": 102, "name": "Ain Diss" },
    { "id": 103, "name": "Fkirina" }, { "id": 104, "name": "Souk Naamane" }, { "id": 105, "name": "Zorg" },
    { "id": 106, "name": "El Fedjoudj Boughrara Saoudi" }, { "id": 107, "name": "Ouled Zouai" }, { "id": 108, "name": "Bir Chouhada" },
    { "id": 109, "name": "Ksar Sbahi" }, { "id": 110, "name": "Oued Nini" }, { "id": 111, "name": "Meskiana" },
    { "id": 112, "name": "Ain Fekroun" }, { "id": 113, "name": "Rahia" }, { "id": 114, "name": "Guettara" },
    { "id": 115, "name": "El Harmilia" }, { "id": 116, "name": "Ouled Gacem" }
  ]},
  { "id": 5, "name": "Batna", "baladiyas": [
    { "id": 117, "name": "Batna" }, { "id": 118, "name": "Ghassira" }, { "id": 119, "name": "Maafa" },
    { "id": 120, "name": "Merouana" }, { "id": 121, "name": "Seriana" }, { "id": 122, "name": "Menaa" },
    { "id": 123, "name": "El Madher" }, { "id": 124, "name": "Tazoult" }, { "id": 125, "name": "N'Gaous" },
    { "id": 126, "name": "Guigba" }, { "id": 127, "name": "Inoughissen" }, { "id": 128, "name": "Arris" },
    { "id": 129, "name": "Ain Djasser" }, { "id": 130, "name": "Ouled Sellam" }, { "id": 131, "name": "Tigherghar" },
    { "id": 132, "name": "Ain Yagout" }, { "id": 133, "name": "Fesdis" }, { "id": 134, "name": "Sefiane" },
    { "id": 135, "name": "Rahbat" }, { "id": 136, "name": "Tighanimine" }, { "id": 137, "name": "Lemsane" },
    { "id": 138, "name": "Ksar Bellezma" }, { "id": 139, "name": "Seggana" }, { "id": 140, "name": "Ichmoul" },
    { "id": 141, "name": "Foum Toub" }, { "id": 142, "name": "Ben Foudhala El Hakania" }, { "id": 143, "name": "Ouyoun El Assafir" },
    { "id": 144, "name": "Djerma" }, { "id": 145, "name": "Bitam" }, { "id": 146, "name": "Metkaouak" },
    { "id": 147, "name": "Barika" }, { "id": 148, "name": "Bouzina" }, { "id": 149, "name": "Chemora" },
    { "id": 150, "name": "Oued Chaaba" }, { "id": 151, "name": "Talkhamt" }, { "id": 152, "name": "Boumaguer" },
    { "id": 153, "name": "Chir" }, { "id": 154, "name": "Teniet El Abed" }, { "id": 155, "name": "Oued Taga" },
    { "id": 156, "name": "Ouled Aouf" }, { "id": 157, "name": "Boumia" }, { "id": 158, "name": "Timgad" },
    { "id": 159, "name": "Ras El Aioun" }, { "id": 160, "name": "Hidoussa" }, { "id": 161, "name": "Kimmel" },
    { "id": 162, "name": "Behir El Chergui" }, { "id": 163, "name": "El Hassi" }, { "id": 164, "name": "Lazrou" },
    { "id": 165, "name": "Bouarif" }, { "id": 166, "name": "Larbaa" }, { "id": 167, "name": "Boulhilat" },
    { "id": 168, "name": "Zanet El Beida" }, { "id": 169, "name": "M'doukel" }, { "id": 170, "name": "Ouled Fadel" },
    { "id": 171, "name": "Taxlent" }, { "id": 172, "name": "Gosbat" }, { "id": 173, "name": "Ouled Ammar" },
    { "id": 174, "name": "Tilatou" }, { "id": 175, "name": "Ain Touta" }, { "id": 176, "name": "Oued El Ma" },
    { "id": 177, "name": "Rassira" }
  ]},
  { "id": 6, "name": "Béjaïa", "baladiyas": [
    { "id": 178, "name": "Bejaia" }, { "id": 179, "name": "Amizour" }, { "id": 180, "name": "Ferraoun" },
    { "id": 181, "name": "Taourirt Ighil" }, { "id": 182, "name": "Chellata" }, { "id": 183, "name": "Tamokra" },
    { "id": 184, "name": "Timezrit" }, { "id": 185, "name": "Souk El Tenine" }, { "id": 186, "name": "M'cisna" },
    { "id": 187, "name": "Tinabdher" }, { "id": 188, "name": "Tichy" }, { "id": 189, "name": "Semaoun" },
    { "id": 190, "name": "Kendira" }, { "id": 191, "name": "Tifra" }, { "id": 192, "name": "Ighram" },
    { "id": 193, "name": "Amalou" }, { "id": 194, "name": "Ighil Ali" }, { "id": 195, "name": "Fenaia Il Maten" },
    { "id": 196, "name": "Toudja" }, { "id": 197, "name": "Darguina" }, { "id": 198, "name": "Sidi Ayad" },
    { "id": 199, "name": "Aokas" }, { "id": 200, "name": "Beni Djellil" }, { "id": 201, "name": "Adekar" },
    { "id": 202, "name": "Akbou" }, { "id": 203, "name": "Seddouk" }, { "id": 204, "name": "Tazmalt" },
    { "id": 205, "name": "Ait R'zine" }, { "id": 206, "name": "Chemini" }, { "id": 207, "name": "Souk Oufella" },
    { "id": 208, "name": "Tibane" }, { "id": 209, "name": "Tala Hamza" }, { "id": 210, "name": "Barbacha" },
    { "id": 211, "name": "Beni Ksila" }, { "id": 212, "name": "Ouzellaguen" }, { "id": 213, "name": "Bouhamza" },
    { "id": 214, "name": "Beni Melikeche" }, { "id": 215, "name": "Sidi Aich" }, { "id": 216, "name": "El Kseur" },
    { "id": 217, "name": "Melbou" }, { "id": 218, "name": "Akfadou" }, { "id": 219, "name": "Leflaye" },
    { "id": 220, "name": "Kherrata" }, { "id": 221, "name": "Dra El Caid" }, { "id": 222, "name": "Tamridjet" },
    { "id": 223, "name": "Ait Smail" }, { "id": 224, "name": "Boukhelifa" }, { "id": 225, "name": "Tizi N'Berber" },
    { "id": 226, "name": "Beni Maouche" }, { "id": 227, "name": "Oued Ghir" }, { "id": 228, "name": "Taskriout" },
    { "id": 229, "name": "Ait Melloul" }
  ]},
  { "id": 7, "name": "Biskra", "baladiyas": [
    { "id": 230, "name": "Biskra" }, { "id": 231, "name": "Oumache" }, { "id": 232, "name": "Branis" },
    { "id": 233, "name": "Chetma" }, { "id": 234, "name": "El Hadjab" }, { "id": 235, "name": "Sidi Okba" },
    { "id": 236, "name": "M'chouneche" }, { "id": 237, "name": "El Haouch" }, { "id": 238, "name": "Ain Naga" },
    { "id": 239, "name": "Zeribet El Oued" }, { "id": 240, "name": "El Mizaraa" }, { "id": 241, "name": "Foughala" },
    { "id": 242, "name": "Djemorah" }, { "id": 243, "name": "Tolga" }, { "id": 244, "name": "Bordj Ben Azzouz" },
    { "id": 245, "name": "Lichana" }, { "id": 246, "name": "El Outaya" }, { "id": 247, "name": "Bouchagroune" },
    { "id": 248, "name": "Mekhadma" }, { "id": 249, "name": "El Feidh" }, { "id": 250, "name": "Khenguet Sidi Nadji" },
    { "id": 251, "name": "Ouled Djellal" }, { "id": 252, "name": "Doucen" }, { "id": 253, "name": "Chaatet" },
    { "id": 254, "name": "Besbes" }, { "id": 255, "name": "Sidi Khaled" }, { "id": 256, "name": "Ras El Miaad" },
    { "id": 257, "name": "El Ghrous" }, { "id": 258, "name": "El Kantara" }, { "id": 259, "name": "Ain Zaatout" },
    { "id": 260, "name": "Lioua" }, { "id": 261, "name": "M'lili" }, { "id": 262, "name": "Ourlal" }
  ]},
  { "id": 8, "name": "Béchar", "baladiyas": [
    { "id": 263, "name": "Bechar" }, { "id": 264, "name": "Erg Ferradj" }, { "id": 265, "name": "Ouled Khoudir" },
    { "id": 266, "name": "Meridja" }, { "id": 267, "name": "Timoudi" }, { "id": 268, "name": "Lahmar" },
    { "id": 269, "name": "Beni Abbes" }, { "id": 270, "name": "Beni Ikhlef" }, { "id": 271, "name": "Mechraa Houari Boumediene" },
    { "id": 272, "name": "Kenadsa" }, { "id": 273, "name": "Igli" }, { "id": 274, "name": "Tabelbala" },
    { "id": 275, "name": "Taghit" }, { "id": 276, "name": "El Ouata" }, { "id": 277, "name": "Boukais" },
    { "id": 278, "name": "Mogheul" }, { "id": 279, "name": "Abadla" }, { "id": 280, "name": "Kerzaz" },
    { "id": 281, "name": "Ksabi" }, { "id": 282, "name": "Tamtert" }, { "id": 283, "name": "Beni Ounif" }
  ]},
  { "id": 9, "name": "Blida", "baladiyas": [
    { "id": 284, "name": "Blida" }, { "id": 285, "name": "Chebli" }, { "id": 286, "name": "Bouinan" },
    { "id": 287, "name": "Oued Alleug" }, { "id": 288, "name": "Ouled Yaich" }, { "id": 289, "name": "Chrea" },
    { "id": 290, "name": "El Affroun" }, { "id": 291, "name": "Chiffa" }, { "id": 292, "name": "Hammam Melouane" },
    { "id": 293, "name": "Benkhelil" }, { "id": 294, "name": "Souma" }, { "id": 295, "name": "Mouzaia" },
    { "id": 296, "name": "Souhane" }, { "id": 297, "name": "Meftah" }, { "id": 298, "name": "Ouled Slama" },
    { "id": 299, "name": "Bouarfa" }, { "id": 300, "name": "Beni Tamou" }, { "id": 301, "name": "Bougara" },
    { "id": 302, "name": "Guerrouaou" }, { "id": 303, "name": "Larbaa" }, { "id": 304, "name": "Beni Mered" },
    { "id": 305, "name": "Ain Romana" }, { "id": 306, "name": "Djebabra" }, { "id": 307, "name": "Oued Djer" },
    { "id": 308, "name": "Tamesguida" }
  ]},
  { "id": 10, "name": "Bouira", "baladiyas": [
    { "id": 309, "name": "Bouira" }, { "id": 310, "name": "El Asnam" }, { "id": 311, "name": "Guerrouma" },
    { "id": 312, "name": "Souk El Khemis" }, { "id": 313, "name": "Aomar" }, { "id": 314, "name": "Chorfa" },
    { "id": 315, "name": "Hanif" }, { "id": 316, "name": "Ouled Rached" }, { "id": 317, "name": "Ain Laloui" },
    { "id": 318, "name": "Hadjera Zerga" }, { "id": 319, "name": "Mezdour" }, { "id": 320, "name": "Haizer" },
    { "id": 321, "name": "Lakhdaria" }, { "id": 322, "name": "Maala" }, { "id": 323, "name": "El Mokrani" },
    { "id": 324, "name": "Ain El Hadjar" }, { "id": 325, "name": "Aghbalou" }, { "id": 326, "name": "Taghzout" },
    { "id": 327, "name": "Raouraoua" }, { "id": 328, "name": "El Adjiba" }, { "id": 329, "name": "Dechmia" },
    { "id": 330, "name": "Ridane" }, { "id": 331, "name": "Bechloul" }, { "id": 332, "name": "Bouderbala" },
    { "id": 333, "name": "El Khabouzia" }, { "id": 334, "name": "Ain Turk" }, { "id": 335, "name": "Saharidj" },
    { "id": 336, "name": "M'chedallah" }, { "id": 337, "name": "Dirah" }, { "id": 338, "name": "El Hachimia" },
    { "id": 339, "name": "Maamora" }, { "id": 340, "name": "Kadiria" }, { "id": 341, "name": "Djebahia" },
    { "id": 342, "name": "Bir Ghbalou" }, { "id": 343, "name": "Taguedit" }, { "id": 344, "name": "Ath Mansour" },
    { "id": 345, "name": "Ait Laaziz" }, { "id": 346, "name": "Boukram" }, { "id": 347, "name": "Sour El Ghozlane" },
    { "id": 348, "name": "Z'barbar" }, { "id": 349, "name": "Oued El Berdi" }, { "id": 350, "name": "El Hakimia" },
    { "id": 351, "name": "Ain Bessam" }, { "id": 352, "name": "El Mesdour" }, { "id": 353, "name": "El Bouna" }
  ]},
  { "id": 11, "name": "Tamanrasset", "baladiyas": [
    { "id": 354, "name": "Tamanrasset" }, { "id": 355, "name": "Ain Amguel" }, { "id": 356, "name": "Idles" },
    { "id": 357, "name": "Abelsa" }, { "id": 358, "name": "Tazrouk" }, { "id": 359, "name": "Ain Salah" },
    { "id": 360, "name": "Ain Guezzam" }, { "id": 361, "name": "Foggaret Ezzaouia" }, { "id": 362, "name": "Tin Zaouatine" },
    { "id": 363, "name": "Inghar" }
  ]},
  { "id": 12, "name": "Tébessa", "baladiyas": [
    { "id": 364, "name": "Tebessa" }, { "id": 365, "name": "Bir El Ater" }, { "id": 366, "name": "Cheria" },
    { "id": 367, "name": "Stah Guentis" }, { "id": 368, "name": "El Aouinet" }, { "id": 369, "name": "El Houidjbet" },
    { "id": 370, "name": "Safsaf El Ouesra" }, { "id": 371, "name": "Hammamet" }, { "id": 372, "name": "Negrine" },
    { "id": 373, "name": "Bir Mokkadem" }, { "id": 374, "name": "El Kouif" }, { "id": 375, "name": "Morsott" },
    { "id": 376, "name": "Telidjene" }, { "id": 377, "name": "Ain Zerga" }, { "id": 378, "name": "Ouenza" },
    { "id": 379, "name": "El Ma Labiodh" }, { "id": 380, "name": "Oum Ali" }, { "id": 381, "name": "Tlidjene" },
    { "id": 382, "name": "El Ogla" }, { "id": 383, "name": "Bekkaria" }, { "id": 384, "name": "Boulhaf Dyr" },
    { "id": 385, "name": "El Mezeraa" }, { "id": 386, "name": "Boukhadra" }, { "id": 387, "name": "Guorriguer" },
    { "id": 388, "name": "Bir Dheb" }, { "id": 389, "name": "Ogla Melha" }, { "id": 390, "name": "Ferkane" },
    { "id": 391, "name": "El Malabiod" }
  ]},
  { "id": 13, "name": "Tlemcen", "baladiyas": [
    { "id": 392, "name": "Tlemcen" }, { "id": 393, "name": "Beni Mester" }, { "id": 394, "name": "Ain Tallout" },
    { "id": 395, "name": "Remchi" }, { "id": 396, "name": "El Fehoul" }, { "id": 397, "name": "Sabra" },
    { "id": 398, "name": "Ghazaouet" }, { "id": 399, "name": "Souani" }, { "id": 400, "name": "Djebala" },
    { "id": 401, "name": "El Gor" }, { "id": 402, "name": "Oued Chouly" }, { "id": 403, "name": "Ain Fetah" },
    { "id": 404, "name": "Ain Ghoraba" }, { "id": 405, "name": "Chetouane" }, { "id": 406, "name": "Mansourah" },
    { "id": 407, "name": "Beni Snous" }, { "id": 408, "name": "Azails" }, { "id": 409, "name": "Sebdou" },
    { "id": 410, "name": "Beni Bahdel" }, { "id": 411, "name": "Beni Khellad" }, { "id": 412, "name": "Honnaine" },
    { "id": 413, "name": "Beni Ouarsous" }, { "id": 414, "name": "Sidi Djillali" }, { "id": 415, "name": "Bouhlou" },
    { "id": 416, "name": "Maghnia" }, { "id": 417, "name": "Hammam Boughrara" }, { "id": 418, "name": "Souk Tleta" },
    { "id": 419, "name": "Ain Fares" }, { "id": 420, "name": "Sidi Medjahed" }, { "id": 421, "name": "Bensekrane" },
    { "id": 422, "name": "Ain Kebira" }, { "id": 423, "name": "Ain Youcef" }, { "id": 424, "name": "Zenata" },
    { "id": 425, "name": "Ouled Riyah" }, { "id": 426, "name": "Bouihi" }, { "id": 427, "name": "Hennaya" },
    { "id": 428, "name": "Ouled Mimoun" }, { "id": 429, "name": "Amieur" }, { "id": 430, "name": "Ain Fezza" },
    { "id": 431, "name": "Fellaoucene" }, { "id": 432, "name": "Sidi Abdelli" }, { "id": 433, "name": "Souk El Khemis" },
    { "id": 434, "name": "Dar Yaghmouracene" }, { "id": 435, "name": "Terny Beni Hediel" }, { "id": 436, "name": "Marsa Ben M'hidi" },
    { "id": 437, "name": "Sidi Kacem" }, { "id": 438, "name": "Souahlia" }, { "id": 439, "name": "Tianet" },
    { "id": 440, "name": "Nedroma" }, { "id": 441, "name": "Beni Smiel" }, { "id": 442, "name": "El Aricha" },
    { "id": 443, "name": "Bab El Assa" }, { "id": 444, "name": "MSirda Fouaga" }
  ]},
  { "id": 14, "name": "Tiaret", "baladiyas": [
    { "id": 445, "name": "Tiaret" }, { "id": 446, "name": "Medroussa" }, { "id": 447, "name": "Ain Deheb" },
    { "id": 448, "name": "Chehaima" }, { "id": 449, "name": "Rechaiga" }, { "id": 450, "name": "Mellakou" },
    { "id": 451, "name": "Sebaine" }, { "id": 452, "name": "Tousnina" }, { "id": 453, "name": "Meghila" },
    { "id": 454, "name": "Sebt" }, { "id": 455, "name": "Sidi Hosni" }, { "id": 456, "name": "Ain El Hadid" },
    { "id": 457, "name": "Frenda" }, { "id": 458, "name": "Ain Kermes" }, { "id": 459, "name": "Ksar Chellala" },
    { "id": 460, "name": "Guertoufa" }, { "id": 461, "name": "Serghine" }, { "id": 462, "name": "Zmalet El Emir Abdelkader" },
    { "id": 463, "name": "Madna" }, { "id": 464, "name": "Sougueur" }, { "id": 465, "name": "Faidja" },
    { "id": 466, "name": "Si Abdelghani" }, { "id": 467, "name": "Ain Bouchekif" }, { "id": 468, "name": "Dahmouni" },
    { "id": 469, "name": "Rahouia" }, { "id": 470, "name": "Mahdia" }, { "id": 471, "name": "Ain Dzarit" },
    { "id": 472, "name": "Sidi Ali Mellal" }, { "id": 473, "name": "Nadorah" }, { "id": 474, "name": "Tagdempt" },
    { "id": 475, "name": "Oued Lilli" }, { "id": 476, "name": "Sidi Bakhti" }, { "id": 477, "name": "Mechraa Safa" },
    { "id": 478, "name": "Djillali Ben Amar" }, { "id": 479, "name": "Sidi Abderrahmane" }, { "id": 480, "name": "Medrissa" },
    { "id": 481, "name": "Faidja" }, { "id": 482, "name": "Takhemaret" }, { "id": 483, "name": "Sidi Ameur" },
    { "id": 484, "name": "Naima" }, { "id": 485, "name": "Ain Beida" }, { "id": 486, "name": "Ouanougha" }
  ]},
  { "id": 15, "name": "Tizi Ouzou", "baladiyas": [
    { "id": 487, "name": "Tizi Ouzou" }, { "id": 488, "name": "Ain El Hammam" }, { "id": 489, "name": "Akbil" },
    { "id": 490, "name": "Freha" }, { "id": 491, "name": "Souamaa" }, { "id": 492, "name": "Mechtras" },
    { "id": 493, "name": "Irdjen" }, { "id": 494, "name": "Timizart" }, { "id": 495, "name": "Makouda" },
    { "id": 496, "name": "Dra" }, { "id": 497, "name": "Beni Aissi" }, { "id": 498, "name": "Beni Zikki" },
    { "id": 499, "name": "Boudjima" }, { "id": 500, "name": "Ain Zaouia" }, { "id": 501, "name": "Azzefoun" },
    { "id": 502, "name": "Tigzirt" }, { "id": 503, "name": "Beni Douala" }, { "id": 504, "name": "Ouaguenoun" },
    { "id": 505, "name": "Ifigha" }, { "id": 506, "name": "Ait Yahia" }, { "id": 507, "name": "Tizi Gheniff" },
    { "id": 508, "name": "Iferhounene" }, { "id": 509, "name": "Mekla" }, { "id": 510, "name": "Tizi N'Tleta" },
    { "id": 511, "name": "Beni Zmenzer" }, { "id": 512, "name": "Iflissen" }, { "id": 513, "name": "Beni Yenni" },
    { "id": 514, "name": "Azazga" }, { "id": 515, "name": "Aghribs" }, { "id": 516, "name": "Boghni" },
    { "id": 517, "name": "Tirmitine" }, { "id": 518, "name": "Ait Khellili" }, { "id": 519, "name": "Sidi Naamane" },
    { "id": 520, "name": "Iboudrarene" }, { "id": 521, "name": "Ait Chafaa" }, { "id": 522, "name": "Akerrou" },
    { "id": 523, "name": "Yatafene" }, { "id": 524, "name": "Ait Oumalou" }, { "id": 525, "name": "Yakourene" },
    { "id": 526, "name": "Larbaa Nath Irathen" }, { "id": 527, "name": "Zekri" }, { "id": 528, "name": "Ouacif" },
    { "id": 529, "name": "Ait Bouaddou" }, { "id": 530, "name": "Abi Youcef" }, { "id": 531, "name": "Beni Ourtilane" },
    { "id": 532, "name": "M'kira" }, { "id": 533, "name": "Bounouh" }, { "id": 534, "name": "Draa Ben Khedda" },
    { "id": 535, "name": "Assi Youcef" }, { "id": 536, "name": "Tadmait" }, { "id": 537, "name": "Ait Mahmoud" },
    { "id": 538, "name": "Idjeur" }, { "id": 539, "name": "Maatkas" }, { "id": 540, "name": "Ait Yahia Moussa" },
    { "id": 541, "name": "Souk El Thenine" }, { "id": 542, "name": "Ait Toudert" }, { "id": 543, "name": "Tizi Rached" },
    { "id": 544, "name": "Illilten" }, { "id": 545, "name": "Ouadhia" }, { "id": 546, "name": "Ait Aggouacha" },
    { "id": 547, "name": "Ait Boumahdi" }, { "id": 548, "name": "Agouni Gueghrane" }, { "id": 549, "name": "Ait Aissa Mimoun" },
    { "id": 550, "name": "Beni Amrane" }, { "id": 551, "name": "Illoula Oumalou" }, { "id": 552, "name": "Imsouhal" },
    { "id": 553, "name": "Sidi M'Hamed" }
  ]},
  { "id": 16, "name": "Alger", "baladiyas": [
    { "id": 554, "name": "Alger Centre" }, { "id": 555, "name": "Sidi M'Hamed" }, { "id": 556, "name": "El Madania" },
    { "id": 557, "name": "Hamma-Anassers" }, { "id": 558, "name": "Bab El Oued" }, { "id": 559, "name": "Bologhine" },
    { "id": 560, "name": "Casbah" }, { "id": 561, "name": "Oued Koriche" }, { "id": 562, "name": "Bir Mourad Rais" },
    { "id": 563, "name": "El Biar" }, { "id": 564, "name": "Bouzareah" }, { "id": 565, "name": "Birkhadem" },
    { "id": 566, "name": "El Harrach" }, { "id": 567, "name": "Baraki" }, { "id": 568, "name": "Oued Smar" },
    { "id": 569, "name": "Bachdjerrah" }, { "id": 570, "name": "Hussein Dey" }, { "id": 571, "name": "Kouba" },
    { "id": 572, "name": "Bourouba" }, { "id": 573, "name": "Dar El Beida" }, { "id": 574, "name": "Bab Ezzouar" },
    { "id": 575, "name": "Ben Aknoun" }, { "id": 576, "name": "Dely Ibrahim" }, { "id": 577, "name": "El Hammamet" },
    { "id": 578, "name": "Rais Hamidou" }, { "id": 579, "name": "Djasr Kasentina" }, { "id": 580, "name": "El Mouradia" },
    { "id": 581, "name": "Hydra" }, { "id": 582, "name": "Mohammadia" }, { "id": 583, "name": "Bordj El Kiffan" },
    { "id": 584, "name": "El Magharia" }, { "id": 585, "name": "Beni Messous" }, { "id": 586, "name": "Les Eucalyptus" },
    { "id": 587, "name": "Bordj El Bahri" }, { "id": 588, "name": "El Marsa" }, { "id": 589, "name": "Cheraga" },
    { "id": 590, "name": "Ouled Chebel" }, { "id": 591, "name": "Tessala El Merdja" }, { "id": 592, "name": "Ain Taya" },
    { "id": 593, "name": "Herraoua" }, { "id": 594, "name": "Reghaia" }, { "id": 595, "name": "Rouiba" },
    { "id": 596, "name": "Staoueli" }, { "id": 597, "name": "Souidania" }, { "id": 598, "name": "Zeralda" },
    { "id": 599, "name": "Mahelma" }, { "id": 600, "name": "Rahmania" }, { "id": 601, "name": "Douera" },
    { "id": 602, "name": "Draria" }, { "id": 603, "name": "El Achour" }, { "id": 604, "name": "Baba Hassen" },
    { "id": 605, "name": "Khraicia" }, { "id": 606, "name": "Saoula" }, { "id": 607, "name": "Ain Benian" },
    { "id": 608, "name": "Ouled Fayet" }, { "id": 609, "name": "Sidi Moussa" }, { "id": 610, "name": "Sebala" }
  ]},
  { "id": 17, "name": "Djelfa", "baladiyas": [
    { "id": 611, "name": "Djelfa" }, { "id": 612, "name": "Messaad" }, { "id": 613, "name": "Charef" },
    { "id": 614, "name": "Benyagoub" }, { "id": 615, "name": "El Guedid" }, { "id": 616, "name": "Had Sahary" },
    { "id": 617, "name": "Sidi Baizid" }, { "id": 618, "name": "Faidh El Botma" }, { "id": 619, "name": "Ain El Ibel" },
    { "id": 620, "name": "Moudjebara" }, { "id": 621, "name": "Tadmit" }, { "id": 622, "name": "Zaafrane" },
    { "id": 623, "name": "Hassi Bahbah" }, { "id": 624, "name": "Zaccar" }, { "id": 625, "name": "El Khemis" },
    { "id": 626, "name": "Sed Rahal" }, { "id": 627, "name": "Selmana" }, { "id": 628, "name": "Ain Fekka" },
    { "id": 629, "name": "Bouira Lahdab" }, { "id": 630, "name": "Sidi Ladjel" }, { "id": 631, "name": "Hassi El Euch" },
    { "id": 632, "name": "El Oussara" }, { "id": 633, "name": "Guernini" }, { "id": 634, "name": "Birine" },
    { "id": 635, "name": "Oum Laadham" }, { "id": 636, "name": "Dar Chioukh" }, { "id": 637, "name": "Mliliha" },
    { "id": 638, "name": "Ain Maabed" }, { "id": 639, "name": "Guettara" }, { "id": 640, "name": "Deldoul" },
    { "id": 641, "name": "Douis" }, { "id": 642, "name": "Benhar" }, { "id": 643, "name": "Amourah" },
    { "id": 644, "name": "Zarzour" }, { "id": 645, "name": "Ain Oussera" }, { "id": 646, "name": "El Idrissia" }
  ]},
  { "id": 18, "name": "Jijel", "baladiyas": [
    { "id": 647, "name": "Jijel" }, { "id": 648, "name": "Eraguene" }, { "id": 649, "name": "El Aouana" },
    { "id": 650, "name": "Ziama Mansouriah" }, { "id": 651, "name": "Taher" }, { "id": 652, "name": "Emir Abdelkader" },
    { "id": 653, "name": "Chekfa" }, { "id": 654, "name": "Chahna" }, { "id": 655, "name": "El Milia" },
    { "id": 656, "name": "Sidi Maarouf" }, { "id": 657, "name": "Settara" }, { "id": 658, "name": "El Ancer" },
    { "id": 659, "name": "Sidi Abdelaziz" }, { "id": 660, "name": "Kaous" }, { "id": 661, "name": "Ghebala" },
    { "id": 662, "name": "Bouraoui Belhadef" }, { "id": 663, "name": "Texenna" }, { "id": 664, "name": "Djemaa Beni Habibi" },
    { "id": 665, "name": "Bordj Tahar" }, { "id": 666, "name": "Ouled Yahia Khedrouche" }, { "id": 667, "name": "Boucif Ouled Askeur" },
    { "id": 668, "name": "Selma Benziada" }, { "id": 669, "name": "Ouled Rabah" }, { "id": 670, "name": "Kennar Nouchfi" },
    { "id": 671, "name": "Ouadjana" }, { "id": 672, "name": "El Kennar" }, { "id": 673, "name": "Sidi M'Hamed Benali" },
    { "id": 674, "name": "Boussif Ouled Askeur" }
  ]},
  { "id": 19, "name": "Sétif", "baladiyas": [
    { "id": 675, "name": "Setif" }, { "id": 676, "name": "Ain El Kebira" }, { "id": 677, "name": "Beni Aziz" },
    { "id": 678, "name": "Ouled Si Ahmed" }, { "id": 679, "name": "Boutaleb" }, { "id": 680, "name": "Hammam Guergour" },
    { "id": 681, "name": "Ain Roua" }, { "id": 682, "name": "Draa Kebila" }, { "id": 683, "name": "Beni Ourtilane" },
    { "id": 684, "name": "Ain Lahdjar" }, { "id": 685, "name": "Ain Abessa" }, { "id": 686, "name": "Dehamcha" },
    { "id": 687, "name": "Babor" }, { "id": 688, "name": "Guidjel" }, { "id": 689, "name": "Ain Oulmene" },
    { "id": 690, "name": "El Eulma" }, { "id": 691, "name": "Djemila" }, { "id": 692, "name": "Ain Arnat" },
    { "id": 693, "name": "Amoucha" }, { "id": 694, "name": "Salah Bey" }, { "id": 695, "name": "Ain Azel" },
    { "id": 696, "name": "Guenzet" }, { "id": 697, "name": "Harbil" }, { "id": 698, "name": "Bouandas" },
    { "id": 699, "name": "Hamma" }, { "id": 700, "name": "Maaouia" }, { "id": 701, "name": "Rosfa" },
    { "id": 702, "name": "Talaifacene" }, { "id": 703, "name": "Beni Fouda" }, { "id": 704, "name": "Tachouda" },
    { "id": 705, "name": "Bougaa" }, { "id": 706, "name": "Ain Sebt" }, { "id": 707, "name": "Beni Chebana" },
    { "id": 708, "name": "Bazer Sakhra" }, { "id": 709, "name": "Mezloug" }, { "id": 710, "name": "Ain Legradj" },
    { "id": 711, "name": "Ksar El Abtal" }, { "id": 712, "name": "Ouled Tebben" }, { "id": 713, "name": "Hammam Soukhna" },
    { "id": 714, "name": "Taya" }, { "id": 715, "name": "Bir El Arch" }, { "id": 716, "name": "Serdj El Ghoul" },
    { "id": 717, "name": "Beidha Bordj" }, { "id": 718, "name": "Tella" }, { "id": 719, "name": "Beni Mouhli" },
    { "id": 720, "name": "Ouled Addouane" }, { "id": 721, "name": "Ouled Sabor" }, { "id": 722, "name": "Guellal" },
    { "id": 723, "name": "Kasr El Abtal" }, { "id": 724, "name": "El Ouldja" }, { "id": 725, "name": "Bir Haddada" },
    { "id": 726, "name": "Rasfa" }, { "id": 727, "name": "Oued El Bared" }, { "id": 728, "name": "El Ouricia" },
    { "id": 729, "name": "Tizi N'Bechar" }, { "id": 730, "name": "Ait Naoual Mezada" }, { "id": 731, "name": "Ait Tizi" },
    { "id": 732, "name": "Beni Hocine" }, { "id": 733, "name": "Guedjel" }, { "id": 734, "name": "Guelta Zerka" }
  ]},
  { "id": 20, "name": "Saïda", "baladiyas": [
    { "id": 735, "name": "Saida" }, { "id": 736, "name": "Ouled Khaled" }, { "id": 737, "name": "Ain El Hadjar" },
    { "id": 738, "name": "Moulay Larbi" }, { "id": 739, "name": "Youb" }, { "id": 740, "name": "Doui Thabet" },
    { "id": 741, "name": "Hounet" }, { "id": 742, "name": "Sidi Amar" }, { "id": 743, "name": "Sidi Boubekeur" },
    { "id": 744, "name": "Ouled Brahim" }, { "id": 745, "name": "Tircine" }, { "id": 746, "name": "Maamora" },
    { "id": 747, "name": "El Hassasna" }, { "id": 748, "name": "Ain Sekhouna" }, { "id": 749, "name": "Ain Soltane" },
    { "id": 750, "name": "Sidi Ahmed" }
  ]},
  { "id": 21, "name": "Skikda", "baladiyas": [
    { "id": 751, "name": "Skikda" }, { "id": 752, "name": "Ain Zouit" }, { "id": 753, "name": "El Hadaiek" },
    { "id": 754, "name": "Bouchetata" }, { "id": 755, "name": "Oum Toub" }, { "id": 756, "name": "Beni Oulbane" },
    { "id": 757, "name": "Kerkera" }, { "id": 758, "name": "El Ghedir" }, { "id": 759, "name": "Ain Kechra" },
    { "id": 760, "name": "Ouldja Boulballout" }, { "id": 761, "name": "Ramdane Djamel" }, { "id": 762, "name": "Beni Bechir" },
    { "id": 763, "name": "Sidi Mezghiche" }, { "id": 764, "name": "Emdjez Edchich" }, { "id": 765, "name": "Tamalous" },
    { "id": 766, "name": "Bin El Ouiden" }, { "id": 767, "name": "Zerdazas" }, { "id": 768, "name": "Ouled Hbaba" },
    { "id": 769, "name": "Es Sebt" }, { "id": 770, "name": "Azzaba" }, { "id": 771, "name": "Djendel Saadi Mohamed" },
    { "id": 772, "name": "Ain Charchar" }, { "id": 773, "name": "Bekkouche Lakhdar" }, { "id": 774, "name": "El Marsa" },
    { "id": 775, "name": "Ben Azzouz" }, { "id": 776, "name": "Bordj Sabat" }, { "id": 777, "name": "Collo" },
    { "id": 778, "name": "Beni Zid" }, { "id": 779, "name": "Cheraia" }, { "id": 780, "name": "Ouled Attia" },
    { "id": 781, "name": "Oued Zehour" }, { "id": 782, "name": "Zitouna" }, { "id": 783, "name": "El Arrouch" },
    { "id": 784, "name": "Salah Bouchaour" }, { "id": 785, "name": "Filfila" }, { "id": 786, "name": "Kanoua" },
    { "id": 787, "name": "Kheneg Mayoum" }, { "id": 788, "name": "La Marsa" }
  ]},
  { "id": 22, "name": "Sidi Bel Abbès", "baladiyas": [
    { "id": 789, "name": "Sidi Bel Abbes" }, { "id": 790, "name": "Tessala" }, { "id": 791, "name": "Sidi Brahim" },
    { "id": 792, "name": "Mostefa Ben Brahim" }, { "id": 793, "name": "Tilmouni" }, { "id": 794, "name": "Sidi Lahcene" },
    { "id": 795, "name": "Ain Thrid" }, { "id": 796, "name": "Sfisef" }, { "id": 797, "name": "Boukhanafis" },
    { "id": 798, "name": "Sidi Hamadouche" }, { "id": 799, "name": "Sidi Ali Boussidi" }, { "id": 800, "name": "Lamtar" },
    { "id": 801, "name": "Ben Badis" }, { "id": 802, "name": "Sidi Khaled" }, { "id": 803, "name": "Marhoum" },
    { "id": 804, "name": "Ras El Ma" }, { "id": 805, "name": "Ain El Berd" }, { "id": 806, "name": "Makedra" },
    { "id": 807, "name": "Sidi Ali Benyoub" }, { "id": 808, "name": "Tabia" }, { "id": 809, "name": "Tenira" },
    { "id": 810, "name": "Moulay Slissen" }, { "id": 811, "name": "El Hacaiba" }, { "id": 812, "name": "Hassi Zahana" },
    { "id": 813, "name": "Merine" }, { "id": 814, "name": "Tafissour" }, { "id": 815, "name": "Amarnas" },
    { "id": 816, "name": "Benachiba Chelia" }, { "id": 817, "name": "Teghalimet" }, { "id": 818, "name": "Ain Kada" },
    { "id": 819, "name": "Dhaya" }, { "id": 820, "name": "Sidi Chaib" }, { "id": 821, "name": "Sidi Dahou Zairs" },
    { "id": 822, "name": "Oued Sefioun" }, { "id": 823, "name": "Hassi Mefsoukh" }, { "id": 824, "name": "Bir El Hammam" },
    { "id": 825, "name": "Sidi Yacoub" }, { "id": 826, "name": "Mezaourou" }, { "id": 827, "name": "Ain Adden" },
    { "id": 828, "name": "Oued Taourira" }, { "id": 829, "name": "Zerouala" }, { "id": 830, "name": "Bedrabine El Mokrani" },
    { "id": 831, "name": "Sehala Thaoura" }, { "id": 832, "name": "Belarbi" }, { "id": 833, "name": "Oued Sebaa" },
    { "id": 834, "name": "Redjem Demouche" }, { "id": 835, "name": "Boudjebaa El Bordj" }, { "id": 836, "name": "Chetouane Belaila" },
    { "id": 837, "name": "Ain Tindamine" }, { "id": 838, "name": "M'cid" }, { "id": 839, "name": "El Gaada" },
    { "id": 840, "name": "Bouhenni" }
  ]},
  { "id": 23, "name": "Annaba", "baladiyas": [
    { "id": 841, "name": "Annaba" }, { "id": 842, "name": "Berrahal" }, { "id": 843, "name": "El Hadjar" },
    { "id": 844, "name": "El Bouni" }, { "id": 845, "name": "Seraidi" }, { "id": 846, "name": "Sidi Amar" },
    { "id": 847, "name": "Chetaibi" }, { "id": 848, "name": "Oued El Aneb" }, { "id": 849, "name": "El Karma" },
    { "id": 850, "name": "Eulma" }, { "id": 851, "name": "Treat" }, { "id": 852, "name": "Chorfa" }
  ]},
  { "id": 24, "name": "Guelma", "baladiyas": [
    { "id": 853, "name": "Guelma" }, { "id": 854, "name": "Nechmaya" }, { "id": 855, "name": "Boumahra Ahmed" },
    { "id": 856, "name": "Guelaat Bou Sbaa" }, { "id": 857, "name": "Heliopolis" }, { "id": 858, "name": "El Fedjoudj" },
    { "id": 859, "name": "Beni Mezline" }, { "id": 860, "name": "Bouati Mahmoud" }, { "id": 861, "name": "Ain Sandel" },
    { "id": 862, "name": "Ras El Agba" }, { "id": 863, "name": "Dahouara" }, { "id": 864, "name": "Belkheir" },
    { "id": 865, "name": "Oued Zenati" }, { "id": 866, "name": "Tamlouka" }, { "id": 867, "name": "Ain Reggada" },
    { "id": 868, "name": "Oued Fragha" }, { "id": 869, "name": "Ain Makhlouf" }, { "id": 870, "name": "Bou Hachana" },
    { "id": 871, "name": "Ain Larbi" }, { "id": 872, "name": "Medjez Amar" }, { "id": 873, "name": "Houari Boumediene" },
    { "id": 874, "name": "Bordj Sabath" }, { "id": 875, "name": "Ben Djerrah" }, { "id": 876, "name": "Ain Ben Beida" },
    { "id": 877, "name": "Khezaras" }, { "id": 878, "name": "Hammam Debagh" }, { "id": 879, "name": "Roknia" },
    { "id": 880, "name": "Sellaoua Announa" }, { "id": 881, "name": "Hammam N'Bails" }, { "id": 882, "name": "Oued Cheham" },
    { "id": 883, "name": "Ain Ben Baida" }, { "id": 884, "name": "Medjez Sfa" }, { "id": 885, "name": "Bouhamdane" },
    { "id": 886, "name": "Bouchegouf" }
  ]},
  { "id": 25, "name": "Constantine", "baladiyas": [
    { "id": 887, "name": "Constantine" }, { "id": 888, "name": "Hamma Bouziane" }, { "id": 889, "name": "Didouche Mourad" },
    { "id": 890, "name": "Zighoud Youcef" }, { "id": 891, "name": "Ain Smara" }, { "id": 892, "name": "El Khroub" },
    { "id": 893, "name": "Ain Abid" }, { "id": 894, "name": "Ouled Rahmoune" }, { "id": 895, "name": "Ibn Ziad" },
    { "id": 896, "name": "Messaoud Boudjeriou" }, { "id": 897, "name": "Beni Hamiden" }, { "id": 898, "name": "Ibn Badis" }
  ]},
  { "id": 26, "name": "Médéa", "baladiyas": [
    { "id": 899, "name": "Medea" }, { "id": 900, "name": "Ouzera" }, { "id": 901, "name": "Benchicao" }, { "id": 902, "name": "El Hamdania" },
    { "id": 903, "name": "Tamesguida" }, { "id": 904, "name": "Draa Esmar" }, { "id": 905, "name": "Berrouaghia" },
    { "id": 906, "name": "Ouled Deide" }, { "id": 907, "name": "Zoubiria" }, { "id": 908, "name": "Rebaia" },
    { "id": 909, "name": "Ain Boucif" }, { "id": 910, "name": "Sidi Damed" }, { "id": 911, "name": "El Ouinet" },
    { "id": 912, "name": "Ouled Bouachra" }, { "id": 913, "name": "Ksar El Boukhari" }, { "id": 914, "name": "M'fatha" },
    { "id": 915, "name": "Sanhadja" }, { "id": 916, "name": "Boghar" }, { "id": 917, "name": "Si Mahdjoub" },
    { "id": 918, "name": "Bouaichoune" }, { "id": 919, "name": "Aziz" }, { "id": 920, "name": "Oum El Djalil" },
    { "id": 921, "name": "Derrag" }, { "id": 922, "name": "El Azizia" }, { "id": 923, "name": "Mihoub" },
    { "id": 924, "name": "Mezerana" }, { "id": 925, "name": "Tablat" }, { "id": 926, "name": "El Guelb El Kebir" },
    { "id": 927, "name": "Meghraoua" }, { "id": 928, "name": "Cheniguel" }, { "id": 929, "name": "Ain Ouksir" },
    { "id": 930, "name": "Ouamri" }, { "id": 931, "name": "Oued Harbil" }, { "id": 932, "name": "Hannacha" },
    { "id": 933, "name": "Beni Slimane" }, { "id": 934, "name": "Sidi Naamane" }, { "id": 935, "name": "Bir Ben Laabed" },
    { "id": 936, "name": "El Omaria" }, { "id": 937, "name": "Baata" }, { "id": 938, "name": "Souagui" },
    { "id": 939, "name": "Ouled Brahim" }, { "id": 940, "name": "Seghouane" }, { "id": 941, "name": "Tlatet Eddouar" },
    { "id": 942, "name": "Chahbounia" }, { "id": 943, "name": "Boughezoul" }, { "id": 944, "name": "Bouskene" },
    { "id": 945, "name": "Sidi Zahar" }, { "id": 946, "name": "Medjebar" }, { "id": 947, "name": "Ouled Antar" },
    { "id": 948, "name": "Ouled Hellal" }, { "id": 949, "name": "Kef Lakhdar" }, { "id": 950, "name": "Ain Benian" },
    { "id": 951, "name": "Sedraia" }, { "id": 952, "name": "Khams Djouamaa" }, { "id": 953, "name": "Sidi Ziane" },
    { "id": 954, "name": "Tafraout" }, { "id": 955, "name": "Ouled Maaref" }, { "id": 956, "name": "Bouchrahil" },
    { "id": 957, "name": "Djouab" }, { "id": 958, "name": "Ouled Bounoua" }, { "id": 959, "name": "Aissaouia" },
    { "id": 960, "name": "El Haoudane" }, { "id": 961, "name": "El Abiod" }, { "id": 962, "name": "Bouaiche" }
  ]},
  { "id": 27, "name": "Mostaganem", "baladiyas": [
    { "id": 963, "name": "Mostaganem" }, { "id": 964, "name": "Sayada" }, { "id": 965, "name": "Fornaka" }, { "id": 966, "name": "Ain Nouissy" },
    { "id": 967, "name": "Hassi Mameche" }, { "id": 968, "name": "Ain Tedles" }, { "id": 969, "name": "Sidi Belaattar" },
    { "id": 970, "name": "Oued El Kheir" }, { "id": 971, "name": "Sidi Ali" }, { "id": 972, "name": "Tazgait" },
    { "id": 973, "name": "Stidia" }, { "id": 974, "name": "Ain Boudinar" }, { "id": 975, "name": "Mesra" },
    { "id": 976, "name": "Sirat" }, { "id": 977, "name": "Bouguirat" }, { "id": 978, "name": "Safsaf" },
    { "id": 979, "name": "Souaflia" }, { "id": 980, "name": "Ouled Maallah" }, { "id": 981, "name": "Sidi Lakhdar" },
    { "id": 982, "name": "Hadjadj" }, { "id": 983, "name": "Nekmaria" }, { "id": 984, "name": "Khadra" },
    { "id": 985, "name": "Achaacha" }, { "id": 986, "name": "Ouled Boughalem" }, { "id": 987, "name": "Benabdelmalek Ramdane" },
    { "id": 988, "name": "Mazagran" }, { "id": 989, "name": "Mansourah" }, { "id": 990, "name": "Kheireddine" },
    { "id": 991, "name": "Blad Touahria" }, { "id": 992, "name": "El Ghomri" }, { "id": 993, "name": "Ain Sidi Cherif" },
    { "id": 994, "name": "Hassiane" }
  ]},
  { "id": 28, "name": "M'Sila", "baladiyas": [
    { "id": 995, "name": "M'Sila" }, { "id": 996, "name": "Hammam Dalaa" }, { "id": 997, "name": "Ouled Derraj" }, { "id": 998, "name": "Tarmount" },
    { "id": 999, "name": "M'Tarfa" }, { "id": 1000, "name": "Maadid" }, { "id": 1001, "name": "Ouled Addi Guebala" },
    { "id": 1002, "name": "Belaiba" }, { "id": 1003, "name": "Berhoum" }, { "id": 1004, "name": "Dehahna" },
    { "id": 1005, "name": "Magra" }, { "id": 1006, "name": "El Houamed" }, { "id": 1007, "name": "Chellal" },
    { "id": 1008, "name": "Ouled Madhi" }, { "id": 1009, "name": "M'cif" }, { "id": 1010, "name": "Bouti Sayah" },
    { "id": 1011, "name": "Khoubana" }, { "id": 1012, "name": "Sidi Aissa" }, { "id": 1013, "name": "Ain El Hadjel" },
    { "id": 1014, "name": "Sidi Hadjeres" }, { "id": 1015, "name": "Ouled Mansour" }, { "id": 1016, "name": "Bou Saada" },
    { "id": 1017, "name": "El Hamel" }, { "id": 1018, "name": "Ouanougha" }, { "id": 1019, "name": "Sidi Ameur" },
    { "id": 1020, "name": "Tamsa" }, { "id": 1021, "name": "Ben Srour" }, { "id": 1022, "name": "Mohamed Boudiaf" },
    { "id": 1023, "name": "Ain Fares" }, { "id": 1024, "name": "Ain El Melh" }, { "id": 1025, "name": "Bir Foda" },
    { "id": 1026, "name": "Sidi M'hamed" }, { "id": 1027, "name": "Ain Rich" }, { "id": 1028, "name": "Beni Ilmane" },
    { "id": 1029, "name": "Ouled Slimane" }, { "id": 1030, "name": "Menaa" }, { "id": 1031, "name": "El Djebel" },
    { "id": 1032, "name": "Medjedel" }, { "id": 1033, "name": "Djebel Messaad" }, { "id": 1034, "name": "Slim" },
    { "id": 1035, "name": "Maarif" }, { "id": 1036, "name": "Souamaa" }, { "id": 1037, "name": "Benzouh" },
    { "id": 1038, "name": "Zarzour" }, { "id": 1039, "name": "Oultene" }, { "id": 1040, "name": "Tolba" },
    { "id": 1041, "name": "El Ouldja" }
  ]},
  { "id": 29, "name": "Mascara", "baladiyas": [
    { "id": 1042, "name": "Mascara" }, { "id": 1043, "name": "Bou Hanifia" }, { "id": 1044, "name": "El Guettana" }, { "id": 1045, "name": "Tighennif" },
    { "id": 1046, "name": "Sehailia" }, { "id": 1047, "name": "Sidi Kada" }, { "id": 1048, "name": "El Hachem" },
    { "id": 1049, "name": "Zahana" }, { "id": 1050, "name": "Mohammadia" }, { "id": 1051, "name": "Sidi Abdelmoumen" },
    { "id": 1052, "name": "Ferraguig" }, { "id": 1053, "name": "El Ghomri" }, { "id": 1054, "name": "Sedjerara" },
    { "id": 1055, "name": "Mocta Douz" }, { "id": 1056, "name": "Ain Fares" }, { "id": 1057, "name": "Ain Fekan" },
    { "id": 1058, "name": "El Mamounia" }, { "id": 1059, "name": "Bou Henni" }, { "id": 1060, "name": "Ghriss" },
    { "id": 1061, "name": "Benian" }, { "id": 1062, "name": "Aouf" }, { "id": 1063, "name": "Gharrous" },
    { "id": 1064, "name": "Matemore" }, { "id": 1065, "name": "Sidi Boussaid" }, { "id": 1066, "name": "Makhda" },
    { "id": 1067, "name": "Ain Fras" }, { "id": 1068, "name": "El Keurt" }, { "id": 1069, "name": "El Menaouer" },
    { "id": 1070, "name": "Oued Taria" }, { "id": 1071, "name": "Oggaz" }, { "id": 1072, "name": "Alaimia" },
    { "id": 1073, "name": "Sidi Abdeldjebar" }, { "id": 1074, "name": "Khalouia" }, { "id": 1075, "name": "Ras El Ain Amirouche" },
    { "id": 1076, "name": "Sig" }, { "id": 1077, "name": "Chorfa" }, { "id": 1078, "name": "Bou Hachoune" },
    { "id": 1079, "name": "Oued El Abtal" }, { "id": 1080, "name": "Sidi Abdelkader" }, { "id": 1081, "name": "Ain Ferah" },
    { "id": 1082, "name": "Froha" }, { "id": 1083, "name": "El Bordj" }, { "id": 1084, "name": "Hacine" },
    { "id": 1085, "name": "Nesmot" }, { "id": 1086, "name": "Tizi" }, { "id": 1087, "name": "El Gaada" },
    { "id": 1088, "name": "Guerdjoum" }
  ]},
  { "id": 30, "name": "Ouargla", "baladiyas": [
    { "id": 1089, "name": "Ouargla" }, { "id": 1090, "name": "Rouissat" }, { "id": 1091, "name": "N'goussa" }, { "id": 1092, "name": "Hassi Messaoud" },
    { "id": 1093, "name": "Ain Beida" }, { "id": 1094, "name": "Sidi Khouiled" }, { "id": 1095, "name": "El Borma" },
    { "id": 1096, "name": "Touggourt" }, { "id": 1097, "name": "Nezla" }, { "id": 1098, "name": "Tebesbest" },
    { "id": 1099, "name": "Zaouia El Abidia" }, { "id": 1100, "name": "Megarine" }, { "id": 1101, "name": "Sidi Slimane" },
    { "id": 1102, "name": "Taibet" }, { "id": 1103, "name": "Tamacine" }, { "id": 1104, "name": "Blidet Amor" },
    { "id": 1105, "name": "El Hadjira" }, { "id": 1106, "name": "El Allia" }, { "id": 1107, "name": "M'naguer" },
    { "id": 1108, "name": "Hassi Ben Abdellah" }, { "id": 1109, "name": "Benaceur" }
  ]},
  { "id": 31, "name": "Oran", "baladiyas": [
    { "id": 1110, "name": "Oran" }, { "id": 1111, "name": "Gdyel" }, { "id": 1112, "name": "Bir El Djir" }, { "id": 1113, "name": "Hassi Bounif" },
    { "id": 1114, "name": "Sidi Chami" }, { "id": 1115, "name": "Arzew" }, { "id": 1116, "name": "Bethioua" },
    { "id": 1117, "name": "Marsat El Hadjadj" }, { "id": 1118, "name": "Ain Turk" }, { "id": 1119, "name": "El Ancor" },
    { "id": 1120, "name": "Oued Tlelat" }, { "id": 1121, "name": "Tafraoui" }, { "id": 1122, "name": "Sidi Ben Yebka" },
    { "id": 1123, "name": "Mers El Kebir" }, { "id": 1124, "name": "Bousfer" }, { "id": 1125, "name": "Ain El Kerma" },
    { "id": 1126, "name": "El Braya" }, { "id": 1127, "name": "Boufatis" }, { "id": 1128, "name": "Hassi Mefsoukh" },
    { "id": 1129, "name": "Sidi Maarouf" }, { "id": 1130, "name": "Ain El Bia" }, { "id": 1131, "name": "Es Senia" },
    { "id": 1132, "name": "Misserghin" }, { "id": 1133, "name": "Boutlelis" }, { "id": 1134, "name": "Hassi Ben Okba" },
    { "id": 1135, "name": "Ben Freha" }
  ]},
  { "id": 32, "name": "El Bayadh", "baladiyas": [
    { "id": 1136, "name": "El Bayadh" }, { "id": 1137, "name": "Rogassa" }, { "id": 1138, "name": "Stitten" }, { "id": 1139, "name": "Brezina" },
    { "id": 1140, "name": "Ghassoul" }, { "id": 1141, "name": "Boualem" }, { "id": 1142, "name": "El Bnoud" },
    { "id": 1143, "name": "Cheguig" }, { "id": 1144, "name": "Sidi Ameur" }, { "id": 1145, "name": "Bougtob" },
    { "id": 1146, "name": "El Kheiter" }, { "id": 1147, "name": "Kef El Ahmar" }, { "id": 1148, "name": "Boussemghoun" },
    { "id": 1149, "name": "Chellala" }, { "id": 1150, "name": "Kraakda" }, { "id": 1151, "name": "El Mehara" },
    { "id": 1152, "name": "Tousmouline" }, { "id": 1153, "name": "Sidi Slimane" }, { "id": 1154, "name": "Sidi Tifour" },
    { "id": 1155, "name": "Mouilha" }, { "id": 1156, "name": "Ain El Orak" }, { "id": 1157, "name": "Arbaouat" }
  ]},
  { "id": 33, "name": "Illizi", "baladiyas": [
    { "id": 1158, "name": "Illizi" }, { "id": 1159, "name": "Djanet" }, { "id": 1160, "name": "Debdeb" }, { "id": 1161, "name": "Bordj Omar Driss" },
    { "id": 1162, "name": "Bordj El Haouas" }, { "id": 1163, "name": "In Amenas" }
  ]},
  { "id": 34, "name": "Bordj Bou Arreridj", "baladiyas": [
    { "id": 1164, "name": "Bordj Bou Arreridj" }, { "id": 1165, "name": "Ain Tesra" }, { "id": 1166, "name": "Ras El Oued" },
    { "id": 1167, "name": "Ain Taghrout" }, { "id": 1168, "name": "Bordj Ghedir" }, { "id": 1169, "name": "Sidi Embarek" },
    { "id": 1170, "name": "El Hamadia" }, { "id": 1171, "name": "Belimour" }, { "id": 1172, "name": "Medjana" },
    { "id": 1173, "name": "Teniet En Nasr" }, { "id": 1174, "name": "Djaafra" }, { "id": 1175, "name": "El Main" },
    { "id": 1176, "name": "El Achir" }, { "id": 1177, "name": "Hasnaoua" }, { "id": 1178, "name": "Khelil" },
    { "id": 1179, "name": "El Anseur" }, { "id": 1180, "name": "Ouled Brahem" }, { "id": 1181, "name": "Mansoura" },
    { "id": 1182, "name": "Haraza" }, { "id": 1183, "name": "Ouled Dahmane" }, { "id": 1184, "name": "Ben Daoud" },
    { "id": 1185, "name": "El M'hir" }, { "id": 1186, "name": "Ouled Sidi Brahim" }, { "id": 1187, "name": "Tefreg" },
    { "id": 1188, "name": "Colla" }, { "id": 1189, "name": "Tixter" }, { "id": 1190, "name": "Bordj Zemmoura" },
    { "id": 1191, "name": "Taglait" }, { "id": 1192, "name": "Ghailasa" }, { "id": 1193, "name": "Rabta" },
    { "id": 1194, "name": "El Euch" }, { "id": 1195, "name": "Ksour" }, { "id": 1196, "name": "Bir Kasdali" },
    { "id": 1197, "name": "Ait R'zine" }
  ]},
  { "id": 35, "name": "Boumerdès", "baladiyas": [
    { "id": 1198, "name": "Boumerdes" }, { "id": 1199, "name": "Boudouaou" }, { "id": 1200, "name": "Afir" },
    { "id": 1201, "name": "Ben Choud" }, { "id": 1202, "name": "Dellys" }, { "id": 1203, "name": "Zemmouri" },
    { "id": 1204, "name": "Si Mustapha" }, { "id": 1205, "name": "Isser" }, { "id": 1206, "name": "Thenia" },
    { "id": 1207, "name": "Timezrit" }, { "id": 1208, "name": "Corso" }, { "id": 1209, "name": "Tidjelabine" },
    { "id": 1210, "name": "Naciria" }, { "id": 1211, "name": "Bordj Menaiel" }, { "id": 1212, "name": "Leghata" },
    { "id": 1213, "name": "Khemis El Khechna" }, { "id": 1214, "name": "Ouled Moussa" }, { "id": 1215, "name": "Larbatache" },
    { "id": 1216, "name": "Hammedi" }, { "id": 1217, "name": "Ouled Hedadj" }, { "id": 1218, "name": "El Kharrouba" },
    { "id": 1219, "name": "Boudouaou El Bahri" }, { "id": 1220, "name": "Baghlia" }, { "id": 1221, "name": "Sidi Daoud" },
    { "id": 1222, "name": "Djinet" }, { "id": 1223, "name": "Taourga" }, { "id": 1224, "name": "Ouled Aissa" },
    { "id": 1225, "name": "Chabet El Ameur" }, { "id": 1226, "name": "Ammal" }, { "id": 1227, "name": "Beni Amrane" },
    { "id": 1228, "name": "Souk El Had" }, { "id": 1229, "name": "El Figuier" }
  ]},
  { "id": 36, "name": "El Tarf", "baladiyas": [
    { "id": 1230, "name": "El Tarf" }, { "id": 1231, "name": "Ain El Assel" }, { "id": 1232, "name": "Bougous" }, { "id": 1233, "name": "El Kala" },
    { "id": 1234, "name": "Souarekh" }, { "id": 1235, "name": "Raml Souk" }, { "id": 1236, "name": "El Aioun" },
    { "id": 1237, "name": "Besbes" }, { "id": 1238, "name": "Asfour" }, { "id": 1239, "name": "Ben Mehidi" },
    { "id": 1240, "name": "Berrihane" }, { "id": 1241, "name": "Echatt" }, { "id": 1242, "name": "Drean" },
    { "id": 1243, "name": "Chihani" }, { "id": 1244, "name": "Chebaita Mokhtar" }, { "id": 1245, "name": "Ain Kerma" },
    { "id": 1246, "name": "Bouhadjar" }, { "id": 1247, "name": "Hammam Beni Salah" }, { "id": 1248, "name": "Oued Zitoun" },
    { "id": 1249, "name": "Zerizer" }, { "id": 1250, "name": "Lac des Oiseaux" }, { "id": 1251, "name": "Chefia" },
    { "id": 1252, "name": "Bouteldja" }, { "id": 1253, "name": "Zitouna" }
  ]},
  { "id": 37, "name": "Tindouf", "baladiyas": [
    { "id": 1254, "name": "Tindouf" }, { "id": 1255, "name": "Oum El Assel" }
  ]},
  { "id": 38, "name": "Tissemsilt", "baladiyas": [
    { "id": 1256, "name": "Tissemsilt" }, { "id": 1257, "name": "Ouled Bessam" }, { "id": 1258, "name": "Sidi Abed" },
    { "id": 1259, "name": "Ammari" }, { "id": 1260, "name": "Maacem" }, { "id": 1261, "name": "Sidi Lantri" },
    { "id": 1262, "name": "Bordj El Emir Abdelkader" }, { "id": 1263, "name": "Theniet El Had" }, { "id": 1264, "name": "Sidi Boutouchent" },
    { "id": 1265, "name": "Lazharia" }, { "id": 1266, "name": "Boucaid" }, { "id": 1267, "name": "Lardjem" },
    { "id": 1268, "name": "Melaab" }, { "id": 1269, "name": "Sidi Slimane" }, { "id": 1270, "name": "Beni Chaib" },
    { "id": 1271, "name": "Beni Lahcene" }, { "id": 1272, "name": "Youssoufia" }, { "id": 1273, "name": "Khemisti" },
    { "id": 1274, "name": "El Ain" }, { "id": 1275, "name": "El Malah" }, { "id": 1276, "name": "Ouled Fares" },
    { "id": 1277, "name": "Tamellaht" }
  ]},
  { "id": 39, "name": "El Oued", "baladiyas": [
    { "id": 1278, "name": "El Oued" }, { "id": 1279, "name": "Kouinine" }, { "id": 1280, "name": "Robbah" }, { "id": 1281, "name": "Oued El Alenda" },
    { "id": 1282, "name": "Bayadha" }, { "id": 1283, "name": "Nakhla" }, { "id": 1284, "name": "Guemar" },
    { "id": 1285, "name": "Ourmes" }, { "id": 1286, "name": "Taghzout" }, { "id": 1287, "name": "Debila" },
    { "id": 1288, "name": "Hassani Abdelkrim" }, { "id": 1289, "name": "Hassi Khalifa" }, { "id": 1290, "name": "Taleb Larbi" },
    { "id": 1291, "name": "Douar El Ma" }, { "id": 1292, "name": "Sidi Aoun" }, { "id": 1293, "name": "Magrane" },
    { "id": 1294, "name": "Mih Ouansa" }, { "id": 1295, "name": "El Ogla" }, { "id": 1296, "name": "Reguiba" },
    { "id": 1297, "name": "Hamraia" }, { "id": 1298, "name": "Trifaoui" }, { "id": 1299, "name": "Ben Guecha" },
    { "id": 1300, "name": "Still" }, { "id": 1301, "name": "Tendla" }, { "id": 1302, "name": "Oum Touyour" },
    { "id": 1303, "name": "El M'Ghair" }, { "id": 1304, "name": "Djamaa" }, { "id": 1305, "name": "M'Rara" },
    { "id": 1306, "name": "Sidi Amrane" }, { "id": 1307, "name": "Sidi Khelil" }
  ]},
  { "id": 40, "name": "Khenchela", "baladiyas": [
    { "id": 1308, "name": "Khenchela" }, { "id": 1309, "name": "Ain Touila" }, { "id": 1310, "name": "M'toussa" }, { "id": 1311, "name": "Kais" },
    { "id": 1312, "name": "Taouzient" }, { "id": 1313, "name": "Baghai" }, { "id": 1314, "name": "El Hamma" },
    { "id": 1315, "name": "Ensigha" }, { "id": 1316, "name": "Ouled Rechache" }, { "id": 1317, "name": "El Mahmal" },
    { "id": 1318, "name": "Chechar" }, { "id": 1319, "name": "Djellal" }, { "id": 1320, "name": "Khirane" },
    { "id": 1321, "name": "Babar" }, { "id": 1322, "name": "Tamza" }, { "id": 1323, "name": "Remila" },
    { "id": 1324, "name": "Bouhmama" }, { "id": 1325, "name": "M'sara" }, { "id": 1326, "name": "Yabous" },
    { "id": 1327, "name": "Selma" }, { "id": 1328, "name": "Cheria" }
  ]},
  { "id": 41, "name": "Souk Ahras", "baladiyas": [
    { "id": 1329, "name": "Souk Ahras" }, { "id": 1330, "name": "Sedrata" }, { "id": 1331, "name": "Hanencha" }, { "id": 1332, "name": "Machroha" },
    { "id": 1333, "name": "Ouled Driss" }, { "id": 1334, "name": "Tiffech" }, { "id": 1335, "name": "Zaarouria" },
    { "id": 1336, "name": "Taoura" }, { "id": 1337, "name": "Drea" }, { "id": 1338, "name": "Haddada" },
    { "id": 1339, "name": "Khedara" }, { "id": 1340, "name": "Merahna" }, { "id": 1341, "name": "Ouled Moumene" },
    { "id": 1342, "name": "Bir Bou Haouch" }, { "id": 1343, "name": "M'daourouch" }, { "id": 1344, "name": "Oum El Adhaim" },
    { "id": 1345, "name": "Ain Zana" }, { "id": 1346, "name": "Ain Soltane" }, { "id": 1347, "name": "Quillen" },
    { "id": 1348, "name": "Sidi Fredj" }, { "id": 1349, "name": "Safel El Ouiden" }, { "id": 1350, "name": "Ragouba" },
    { "id": 1351, "name": "Khemissa" }, { "id": 1352, "name": "Oued Keberit" }, { "id": 1353, "name": "Terraguelt" },
    { "id": 1354, "name": "Zouabi" }
  ]},
  { "id": 42, "name": "Tipaza", "baladiyas": [
    { "id": 1355, "name": "Tipaza" }, { "id": 1356, "name": "Menaceur" }, { "id": 1357, "name": "Nador" }, { "id": 1358, "name": "Sidi Amar" },
    { "id": 1359, "name": "Gouraya" }, { "id": 1360, "name": "Aghbal" }, { "id": 1361, "name": "Messelmoun" },
    { "id": 1362, "name": "Sidi Ghiles" }, { "id": 1363, "name": "Cherchell" }, { "id": 1364, "name": "Sidi Semiane" },
    { "id": 1365, "name": "Beni Mileuk" }, { "id": 1366, "name": "Damous" }, { "id": 1367, "name": "Larhat" },
    { "id": 1368, "name": "Hadjout" }, { "id": 1369, "name": "Merad" }, { "id": 1370, "name": "Sidi Rached" },
    { "id": 1371, "name": "Kolea" }, { "id": 1372, "name": "Attatba" }, { "id": 1373, "name": "Chaiba" },
    { "id": 1374, "name": "Fouka" }, { "id": 1375, "name": "Bou Ismail" }, { "id": 1376, "name": "Ain Tagourait" },
    { "id": 1377, "name": "Bou Haroun" }, { "id": 1378, "name": "Khemisti" }, { "id": 1379, "name": "Douaouda" },
    { "id": 1380, "name": "Ahmer El Ain" }, { "id": 1381, "name": "Bourkika" }, { "id": 1382, "name": "Sidi Fredj" }
  ]},
  { "id": 43, "name": "Mila", "baladiyas": [
    { "id": 1383, "name": "Mila" }, { "id": 1384, "name": "Ferdjioua" }, { "id": 1385, "name": "Chelghoum Laid" }, { "id": 1386, "name": "Oued Endja" },
    { "id": 1387, "name": "Tiberguent" }, { "id": 1388, "name": "Bouhatem" }, { "id": 1389, "name": "Rouached" },
    { "id": 1390, "name": "Tassadane Haddada" }, { "id": 1391, "name": "Grarem Gouga" }, { "id": 1392, "name": "Sidi Merouane" },
    { "id": 1393, "name": "Tadjenanet" }, { "id": 1394, "name": "Benyahia Abderrahmane" }, { "id": 1395, "name": "Ouled Khalouf" },
    { "id": 1396, "name": "Teleghma" }, { "id": 1397, "name": "Oued Athmenia" }, { "id": 1398, "name": "Ain Mellouk" },
    { "id": 1399, "name": "Sidi Khelifa" }, { "id": 1400, "name": "Zeghaia" }, { "id": 1401, "name": "Ain Beida Harriche" },
    { "id": 1402, "name": "Yahia Beniguecha" }, { "id": 1403, "name": "Oued Seguen" }, { "id": 1404, "name": "El Mechira" },
    { "id": 1405, "name": "Elayadi Barbes" }, { "id": 1406, "name": "Ain Tine" }, { "id": 1407, "name": "Terrai Bainen" },
    { "id": 1408, "name": "Hamala" }, { "id": 1409, "name": "Tassala Lematai" }, { "id": 1410, "name": "Derradji Bousselah" },
    { "id": 1411, "name": "Minar Zarza" }, { "id": 1412, "name": "Amira Arras" }, { "id": 1413, "name": "Chigara" },
    { "id": 1414, "name": "Tiberguent" }
  ]},
  { "id": 44, "name": "Aïn Defla", "baladiyas": [
    { "id": 1415, "name": "Ain Defla" }, { "id": 1416, "name": "Miliana" }, { "id": 1417, "name": "Khemis Miliana" }, { "id": 1418, "name": "Hammam Righa" },
    { "id": 1419, "name": "Bourached" }, { "id": 1420, "name": "Djelida" }, { "id": 1421, "name": "El Amra" },
    { "id": 1422, "name": "Arib" }, { "id": 1423, "name": "Djendel" }, { "id": 1424, "name": "Oued Chorfa" },
    { "id": 1425, "name": "Bir Ould Khelifa" }, { "id": 1426, "name": "Ain Lechiakh" }, { "id": 1427, "name": "Oued Djemaa" },
    { "id": 1428, "name": "Ain Soltane" }, { "id": 1429, "name": "Tarik Ibn Ziad" }, { "id": 1430, "name": "Bordj Emir Khaled" },
    { "id": 1431, "name": "El Attaf" }, { "id": 1432, "name": "Tiberkanine" }, { "id": 1433, "name": "El Abadia" },
    { "id": 1434, "name": "Boumedfaa" }, { "id": 1435, "name": "Hoceinia" }, { "id": 1436, "name": "Ben Allal" },
    { "id": 1437, "name": "Sidi Lakhdar" }, { "id": 1438, "name": "Ain Benian" }, { "id": 1439, "name": "Bathia" },
    { "id": 1440, "name": "Rouina" }, { "id": 1441, "name": "Zeddine" }, { "id": 1442, "name": "El Hassania" },
    { "id": 1443, "name": "Birbouche" }, { "id": 1444, "name": "Djemaa Ouled Cheikh" }, { "id": 1445, "name": "Mekhatria" },
    { "id": 1446, "name": "Ain Torki" }, { "id": 1447, "name": "El Maine" }, { "id": 1448, "name": "Tacheta Zougagha" },
    { "id": 1449, "name": "Belaas" }, { "id": 1450, "name": "Ouled Melha" }
  ]},
  { "id": 45, "name": "Naâma", "baladiyas": [
    { "id": 1451, "name": "Naama" }, { "id": 1452, "name": "Mecheria" }, { "id": 1453, "name": "Ain Sefra" }, { "id": 1454, "name": "Tiout" },
    { "id": 1455, "name": "Sfissifa" }, { "id": 1456, "name": "Moghrar" }, { "id": 1457, "name": "Asla" },
    { "id": 1458, "name": "Djenienne Bourezg" }, { "id": 1459, "name": "Ain Ben Khelil" }, { "id": 1460, "name": "Makman Ben Amer" },
    { "id": 1461, "name": "Kasdir" }, { "id": 1462, "name": "El Biod" }
  ]},
  { "id": 46, "name": "Aïn Témouchent", "baladiyas": [
    { "id": 1463, "name": "Ain Temouchent" }, { "id": 1464, "name": "Sidi Ben Adda" }, { "id": 1465, "name": "Chaabat El Leham" },
    { "id": 1466, "name": "Chentouf" }, { "id": 1467, "name": "Hammam Bou Hadjar" }, { "id": 1468, "name": "Bouzedjar" },
    { "id": 1469, "name": "Ouled Boudjemaa" }, { "id": 1470, "name": "El Amria" }, { "id": 1471, "name": "Hassi El Ghella" },
    { "id": 1472, "name": "Ouled Kihal" }, { "id": 1473, "name": "Beni Saf" }, { "id": 1474, "name": "Sidi Safi" },
    { "id": 1475, "name": "Oulhaca El Gheraba" }, { "id": 1476, "name": "Ain Kihal" }, { "id": 1477, "name": "Aghlal" },
    { "id": 1478, "name": "Ain Tolba" }, { "id": 1479, "name": "Aoubellil" }, { "id": 1480, "name": "El Malah" },
    { "id": 1481, "name": "Terga" }, { "id": 1482, "name": "Ouled Kihel" }, { "id": 1483, "name": "Sidi Boumediene" },
    { "id": 1484, "name": "El Mesfa" }, { "id": 1485, "name": "Tamzoura" }, { "id": 1486, "name": "Ain El Arbaa" },
    { "id": 1487, "name": "Sidi Ouriache" }, { "id": 1488, "name": "Hassasna" }, { "id": 1489, "name": "M'Said" },
    { "id": 1490, "name": "Emir Abdelkader" }
  ]},
  { "id": 47, "name": "Ghardaïa", "baladiyas": [
    { "id": 1491, "name": "Ghardaia" }, { "id": 1492, "name": "Metlili" }, { "id": 1493, "name": "El Atteuf" }, { "id": 1494, "name": "Bounoura" },
    { "id": 1495, "name": "Dhayet Bendhahoua" }, { "id": 1496, "name": "Berriane" }, { "id": 1497, "name": "Zelfana" },
    { "id": 1498, "name": "Sebseb" }, { "id": 1499, "name": "El Guerrara" }, { "id": 1500, "name": "Mansourah" },
    { "id": 1501, "name": "El Menia" }, { "id": 1502, "name": "Hassi Gara" }, { "id": 1503, "name": "Hassi Fehal" }
  ]},
  { "id": 48, "name": "Relizane", "baladiyas": [
    { "id": 1504, "name": "Relizane" }, { "id": 1505, "name": "Bendaoud" }, { "id": 1506, "name": "Oued Rhiou" }, { "id": 1507, "name": "Merdja Sidi Abed" },
    { "id": 1508, "name": "Oued El Djemaa" }, { "id": 1509, "name": "Ouled Aiche" }, { "id": 1510, "name": "Sidi Saada" },
    { "id": 1511, "name": "El H'madna" }, { "id": 1512, "name": "Sidi M'hamed Benali" }, { "id": 1513, "name": "Mediouna" },
    { "id": 1514, "name": "Beni Zentis" }, { "id": 1515, "name": "Sidi Khettab" }, { "id": 1516, "name": "Ammi Moussa" },
    { "id": 1517, "name": "El Ouldja" }, { "id": 1518, "name": "Ouled Yacoub" }, { "id": 1519, "name": "Zemmora" },
    { "id": 1520, "name": "Dar Ben Abdellah" }, { "id": 1521, "name": "Beni Dergoun" }, { "id": 1522, "name": "Djidiouia" },
    { "id": 1523, "name": "Hamri" }, { "id": 1524, "name": "El Guettar" }, { "id": 1525, "name": "Mazouna" },
    { "id": 1526, "name": "Ain Rahma" }, { "id": 1527, "name": "Yellel" }, { "id": 1528, "name": "Kalaa" },
    { "id": 1529, "name": "Ain Tarek" }, { "id": 1530, "name": "Sidi M'hamed Benaouda" }, { "id": 1531, "name": "Ramka" },
    { "id": 1532, "name": "Mendes" }, { "id": 1533, "name": "Oued Essalem" }, { "id": 1534, "name": "Sidi Lazreg" },
    { "id": 1535, "name": "El Hassi" }, { "id": 1536, "name": "El Matmar" }, { "id": 1537, "name": "Sidi Bouabdelli" },
    { "id": 1538, "name": "Belaassel Bouzagza" }, { "id": 1539, "name": "Souk El Had" }, { "id": 1540, "name": "Had Echkalla" },
    { "id": 1541, "name": "Lahlef" }
  ]},
  { "id": 49, "name": "Timimoun", "baladiyas": [
      { "id": 1542, "name": "Timimoun" }, { "id": 1543, "name": "Ouled Said" }, { "id": 1544, "name": "Metarfa" },
      { "id": 1545, "name": "Ouled Aissa" }, { "id": 1546, "name": "Tinerkouk" }, { "id": 1547, "name": "Ksar Kaddour" },
      { "id": 1548, "name": "Talmine" }, { "id": 1549, "name": "Aougrout" }, { "id": 1550, "name": "Deldoul" },
      { "id": 1551, "name": "Charouine" }
  ]},
  { "id": 50, "name": "Bordj Badji Mokhtar", "baladiyas": [
      { "id": 1552, "name": "Bordj Badji Mokhtar" }, { "id": 1553, "name": "Timiaouine" }
  ]},
  { "id": 51, "name": "Ouled Djellal", "baladiyas": [
      { "id": 1554, "name": "Ouled Djellal" }, { "id": 1555, "name": "Sidi Khaled" }, { "id": 1556, "name": "Ras El Miaad" },
      { "id": 1557, "name": "Besbes" }, { "id": 1558, "name": "Doucen" }, { "id": 1559, "name": "Ech Chaiba" }
  ]},
  { "id": 52, "name": "Béni Abbès", "baladiyas": [
      { "id": 1560, "name": "Béni Abbès" }, { "id": 1561, "name": "Tamtert" }, { "id": 1562, "name": "Ouled Khoudir" },
      { "id": 1563, "name": "Kerzaz" }, { "id": 1564, "name": "El Ouata" }, { "id": 1565, "name": "Igli" },
      { "id": 1566, "name": "Timoudi" }, { "id": 1567, "name": "Ksabi" }, { "id": 1568, "name": "Beni Ikhlef" },
      { "id": 1569, "name": "Erg Ferradj" }
  ]},
  { "id": 53, "name": "In Salah", "baladiyas": [
      { "id": 1570, "name": "In Salah" }, { "id": 1571, "name": "Foggaret Ezzaouia" }, { "id": 1572, "name": "Inghar" }
  ]},
  { "id": 54, "name": "In Guezzam", "baladiyas": [
      { "id": 1573, "name": "In Guezzam" }, { "id": 1574, "name": "Tin Zaouatine" }
  ]},
  { "id": 55, "name": "Touggourt", "baladiyas": [
      { "id": 1575, "name": "Touggourt" }, { "id": 1576, "name": "Nezla" }, { "id": 1577, "name": "Tebesbest" },
      { "id": 1578, "name": "Zaouia El Abidia" }, { "id": 1579, "name": "Megarine" }, { "id": 1580, "name": "Sidi Slimane" },
      { "id": 1581, "name": "Taibet" }, { "id": 1582, "name": "Tamacine" }, { "id": 1583, "name": "Blidet Amor" },
      { "id": 1584, "name": "El Hadjira" }, { "id": 1585, "name": "El Alia" }, { "id": 1586, "name": "M'Naguer" },
      { "id": 1587, "name": "Benaceur" }
  ]},
  { "id": 56, "name": "Djanet", "baladiyas": [
      { "id": 1588, "name": "Djanet" }, { "id": 1589, "name": "Bordj El Haouas" }
  ]},
  { "id": 57, "name": "El M'Ghair", "baladiyas": [
      { "id": 1590, "name": "El M'Ghair" }, { "id": 1591, "name": "Sidi Amrane" }, { "id": 1592, "name": "Sidi Khelil" },
      { "id": 1593, "name": "Still" }, { "id": 1594, "name": "Tendla" }, { "id": 1595, "name": "Oum Touyour" },
      { "id": 1596, "name": "Djamaa" }, { "id": 1597, "name": "M'Rara" }
  ]},
  { "id": 58, "name": "El Meniaa", "baladiyas": [
      { "id": 1598, "name": "El Meniaa" }, { "id": 1599, "name": "Hassi Gara" }, { "id": 1600, "name": "Hassi Fehal" }
  ]}
];
